### ISSUE TITLE
[BUG] SPDK NVMe synchronous calls

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#11096]
Actually , if we have a local logical volume, we export it via nvmf and then attach to it creating a nvme controller, in the same way we do for logical volume that rely on different spdk_tgt instances. Due to the presence of some synchrnous call in the spdk nvme path, we have some issues because the poller which handle the nvmf subsystem and the nvme controller is the same (see https://github.com/spdk/spdk/issues/3540)

- if we try to resize the local logical volume, we get stuck https://github.com/longhorn/longhorn/issues/8022

- during Volume migration negative test cases we get stuck https://github.com/longhorn/longhorn/issues/10800

Actually there is a development under downstream review, https://github.com/longhorn/spdk/pull/52, and upstream review, https://review.spdk.io/c/spdk/spdk/+/25169, which try to remove the synchronous calls that cause these blocks.
For the volume expansion it should be enough, probably there is something further to change to solve also the migration issue.

**Comment by derekbit** [comment]
Blocks https://github.com/longhorn/longhorn/issues/8022

**Comment by DamiaSan** [comment]
Hi @derekbit , in the [issue](https://github.com/spdk/spdk/issues/3673) opened on spdk main repo for our [volume migration issue](https://github.com/longhorn/longhorn/issues/10800), a core maintainer suggest to us to rebase to official master branch because there are some patches just merged that could solve the issue. These commits are not contained in last `v25.05` release, that I think we have plan to rebase to, so what do you suggest do to?

**Comment by derekbit** [comment]
> Hi [@derekbit](https://github.com/derekbit) , in the [issue](https://github.com/spdk/spdk/issues/3673) opened on spdk main repo for our [volume migration issue](https://github.com/longhorn/longhorn/issues/10800), a core maintainer suggest to us to rebase to official master branch because there are some patches just merged that could solve the issue. 

Thanks for the information.
Do you know what the patches are?

**Comment by DamiaSan** [comment]
The patch series is this one: https://review.spdk.io/c/spdk/spdk/+/25907
As we can see [here](https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627), the async connect in nvme_tcp has already been merged in master branch

**Comment by derekbit** [comment]
> The patch series is this one: https://review.spdk.io/c/spdk/spdk/+/25907 As we can see [here](https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627), the async connect in nvme_tcp has already been merged in master branch

Looks good. I'm working on the backport to longhorn-v25.05. We probably can test it this week.

**Comment by DamiaSan** [comment]
> > The patch series is this one: https://review.spdk.io/c/spdk/spdk/+/25907 As we can see [here](https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627), the async connect in nvme_tcp has already been merged in master branch
> 
> Looks good. I'm working on the backport to longhorn-v25.05. We probably can test it this week.

Ok, but the commit useful to solve the issue are not include in v25.05 spdk release

**Comment by derekbit** [comment]
> > > The patch series is this one: https://review.spdk.io/c/spdk/spdk/+/25907 As we can see [here](https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627), the async connect in nvme_tcp has already been merged in master branch
> > 
> > 
> > Looks good. I'm working on the backport to longhorn-v25.05. We probably can test it this week.
> 
> Ok, but the commit useful to solve the issue are not include in v25.05 spdk release

Can you help check if backporting the commits to v25.05 is possible?

**Comment by DamiaSan** [comment]
Sure that it is possible, we should simply align to master branch at commit https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627, which is the last one of the patch series we want to use. Respect to v25.05 release, we have a couple of week of additional commits, and many of them belong to this patch series.
See https://github.com/spdk/spdk/issues/3673#issuecomment-2983218360

**Comment by derekbit** [comment]
> Sure that it is possible, we should simply align to master branch at commit [spdk/spdk@555c962](https://github.com/spdk/spdk/commit/555c96215da5d2716af27f11bd169f832519e627), which is the last one of the patch series we want to use. Respect to v25.05 release, we have a couple of week of additional commits, and many of them belong to this patch series. See [spdk/spdk#3673 (comment)](https://github.com/spdk/spdk/issues/3673#issuecomment-2983218360)

Hello @DamiaSan 
The backport to v25.05 is completed. You can check if the issue is resolved. 
https://github.com/longhorn/spdk

**Comment by DamiaSan** [comment]
What about the volume expansion, the upstream review of the development I started some time ago, https://review.spdk.io/c/spdk/spdk/+/26148,  will be continued by Tomek Zawadzki, a SPDK core maintainer.
What about the volume migration test case, the issue in SPDK has been resolved in last branch `longhorn-v25.05`.
So I close this task.

**Comment by derekbit** [comment]
Keep the ticket opened because it is still an issue in SPDK. We will close it after upstream fixes it.

**Comment by derekbit** [comment]
cc @davidcheng0922

**Comment by derekbit** [comment]
Fixed in the upstream 25.09.
