### ISSUE TITLE
[BUG] Unable to Build Longhorn-Share-Manager Image Due to CMAKE Compatibility

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#11159]
### Describe the Bug

Unable to build longhorn-share-manager image due to cmake compatibility

```
#26 9.822 CMake Error at CMakeLists.txt:26 (cmake_minimum_required):
#26 9.822   Compatibility with CMake < 3.5 has been removed from CMake.
#26 9.822 
#26 9.822   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
#26 9.822   to tell CMake that the project requires at least <min> but has been updated
#26 9.822   to work with policies introduced by <max> or earlier.
#26 9.822 
#26 9.822   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
#26 9.822 
#26 9.822 
#26 9.822 -- Configuring incomplete, errors occurred!
#26 ERROR: process "/bin/sh -c export REPO_OVERRIDE=\"\" &&     export COMMIT_ID_OVERRIDE=\"\" &&     bash /usr/src/dep-versions/scripts/build-nfs-ganesha.sh \"${REPO_OVERRIDE}\" \"${COMMIT_ID_OVERRIDE}\"" did not complete successfully: exit code: 1
------
 > [lib_builder 6/6] RUN export REPO_OVERRIDE="" &&     export COMMIT_ID_OVERRIDE="" &&     bash /usr/src/dep-versions/scripts/build-nfs-ganesha.sh "${REPO_OVERRIDE}" "${COMMIT_ID_OVERRIDE}":
9.822   Compatibility with CMake < 3.5 has been removed from CMake.
9.822 
9.822   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
9.822   to tell CMake that the project requires at least <min> but has been updated
```

### To Reproduce

https://github.com/longhorn/longhorn-share-manager/actions/runs/15843126032/job/44659443365?pr=551

### Expected Behavior

Should be able to build

### Support Bundle for Troubleshooting

N/A

### Environment

- Longhorn version: 
- Impacted volume (PV): 
- Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
- Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
  - Number of control plane nodes in the cluster:
  - Number of worker nodes in the cluster:
- Node config
  - OS type and version:
  - Kernel version:
  - CPU per node:
  - Memory per node:
  - Disk type (e.g. SSD/NVMe/HDD):
  - Network bandwidth between the nodes (Gbps):
- Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
- Number of Longhorn volumes in the cluster:

**Comment by hookak** [comment]
I encountered the same issue while building `longhorn-instance-manager`.
The root cause is that the base image registry.suse.com/bci/bci-base:15.6 installs CMake 4.x by default, which leads to errors when running CMake due to version incompatibility.

**Comment by hookak** [comment]
More specifically, `https://download.opensuse.org/repositories/devel:tools:building/15.6/devel:tools:building.repo`
is added, the available CMake version is upgraded from 3.x to 4.x.
As a result, CMake 4.x gets installed, which causes the compatibility issue during the build.

**Comment by derekbit** [comment]
Thanks @hookak. I will fix both longhorn-share-manager and longhorn-instance-manager.

**Comment by derekbit** [comment]
Hello @hookak 
The issue should be fixed. Can you help check it when you are available? Thanks.

**Comment by hookak** [comment]
@derekbit Yes, the issue occurred in the `build-libjsonc.sh` when building `instance-manager`
It seems the issue is now resolved. Thanks for addressing it so quickly

**Comment by hookak** [comment]
Hello @derekbit 

While building the `longhorn-instance-manager` from the `v1.9.x` branch, I encountered a failure during the `zypper` package installation step, as shown below:

```
#21 ERROR: process "/bin/sh -c zypper -n install cmake gcc gcc13 xsltproc docbook-xsl-stylesheets git python311 python311-pip patchelf fuse3-devel jq wget" did not complete successfully: exit code: 106
...
Dockerfile:61
--------------------
  61 | RUN zypper -n install cmake gcc gcc13 xsltproc docbook-xsl-stylesheets git python311 python311-pip patchelf fuse3-devel jq wget
--------------------
```

Do you alse see the same issue in upstream builds?

**Comment by derekbit** [comment]
> Hello [@derekbit](https://github.com/derekbit)
> 
> While building the `longhorn-instance-manager` from the `v1.9.x` branch, I encountered a failure during the `zypper` package installation step, as shown below:
> 
> ```
> #21 ERROR: process "/bin/sh -c zypper -n install cmake gcc gcc13 xsltproc docbook-xsl-stylesheets git python311 python311-pip patchelf fuse3-devel jq wget" did not complete successfully: exit code: 106
> ...
> Dockerfile:61
> --------------------
>   61 | RUN zypper -n install cmake gcc gcc13 xsltproc docbook-xsl-stylesheets git python311 python311-pip patchelf fuse3-devel jq wget
> --------------------
> ```
> 
> Do you alse see the same issue in upstream builds?

Didn't hit the issue in my local env.
I'm rerunning the build process. Let's see if the issue can be observed.
https://github.com/longhorn/longhorn-instance-manager/actions/runs/15664455547

**Comment by hookak** [comment]
In my environment, I’m still experiencing the issue, but I’ve checked and it looks like the upstream build is fine. Thanks for confirming

**Comment by roger-ryao** [comment]
**Verified on master 20250630**

- dep-versions master https://github.com/longhorn/dep-versions/commit/a97ebc894bc111e3ec96149fe7df81331d83eedf


**The test steps**

https://github.com/longhorn/longhorn/issues/11159#issuecomment-2999587187

**Result Passed**

master-head `longhorn-share-manager` and `longhorn-instance-manager` builds were successful without issues.

1. https://github.com/longhorn/longhorn-share-manager/actions/runs/15953462074/job/44996640234
2. https://github.com/longhorn/longhorn-instance-manager/actions/runs/15951859596/job/44993002791
