### ISSUE TITLE
[BUG] Scheduled backups didn't complete and leave tons of snapshots behind

### ISSUE THREAD

**Issue by FCarvMobil** [longhorn/longhorn#2029]
Hi guys, don't know if it is a bug or not.
Most of the 37 volumes running at the K8s cluster had some backup schedule assigned to.

About 9 of them are suffering from some issue where the backup operation didn't occur and leave behind a lot of snapshots (4 snapshots for each backup execution for each volume) and they must be deleted manually, pretty much like in #1826 
![image](https://user-images.githubusercontent.com/68639314/101001025-8765fe00-3556-11eb-87d0-f264068a1d3c.png)
And the backup doesn't occur:
![image](https://user-images.githubusercontent.com/68639314/101001329-e3308700-3556-11eb-9a33-8ce689ad580f.png)

What I noticed is that the pod created by the job to run the backup **fails**; each time this pod runs it takes a snapshot then fail and restart, it does this 4 times and this is why I come up with 4 new snapshots each backup run.

I'd picked one workload, stopped then started its pod and run again a scheduled backup. It ran ok. But this doesn't worked for all the others. 
These 9 volumes hosts 2 types of workloads but I have other volumes for the same workload types that runs its scheduled backups ok. Other thing to consider is that some of them are 'old' and others were created a few days ago.
The failing backup pods throw this error before restart:
```
time="2020-12-02T13:05:57Z" 
level=fatal msg="Error taking snapshot: failed to complete backupAndCleanup for pvc-c0acdcbc-f258-4764-8ef5-68214842df74: Post \"http://longhorn-backend:9500/v1/volumes/pvc-c0acdcbc-f258-4764-8ef5-68214842df74?action=snapshotCreate\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

Any idea of what is happening? How can I diagnose / debug what's going on at the backup pod or the volume itself?

Thanks for the attention and best regards,
Fabio Carvalho

**Comment by shuo-wu** [comment]
Can you provide the support bundle if possible? I didn't find any important clues based on the current info. 

As for debugging this issue, you may need to know that Longhorn will do snapshot creation before each backup. In this case, the recurring backup failed at the snapshot creation part (timeout error). But it seems that the snapshot is actually created even if there is a timeout error. I may need to dive into the support bundle to see if this timeout error is caused by the network connection or there are any other unexpected issues.

**Comment by FCarvMobil** [comment]
Hi @shuo-wu ! Thanks for replying.
It's ok to provide a support bundle. How can I send you the file? It has 27MB.

Another thing i've noticed is that the proxy settings for longhorn-manager were inaccurate, so one of the cluster nodes (there are 3) wasn't covered by the proxy exceptions (this is something at this particular cluster that is annoying). 
So a few hours ago I bring down all workloads then edit the longhorn-manager daemonset to correct the 'no_proxy' env var.

After bringing up all workloads I'd tested again (changing the schedule from one affected volume) but it didn't work, same behavior.

Thanks again! Please let me know how to send you the support bundle file.

**Comment by PhanLe1010** [comment]
@FCarvMobil 
Can you please send it to longhorn-support-bundle@rancher.com ?

**Comment by shuo-wu** [comment]
For the proxying setting issue, I am not sure which part you are worried about. Typically proxy setting is related to Longhorn UI rather than longhorn manager daemonset. If possible, you can file a separate post to track the proxy issue.

**Comment by shuo-wu** [comment]
1. According to the log instance manager pods, the engine and replicas succeeded to create 4 snapshots around `2020-12-02T13:05:57Z`. It means the volume snapshot creation works fine, and the issue is not caused by the interval network disconnection.
```
2020-12-02T13:05:34.462194841Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:05:34Z" level=info msg="Snapshot: 10.40.0.24:10000 c-9cfdm0-ea8d222d UserCreated true Created at 2020-12-02T13:05:34Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:05:34.46362084Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:05:34Z" level=info msg="Snapshot: 10.32.0.19:10375 c-9cfdm0-ea8d222d UserCreated true Created at 2020-12-02T13:05:34Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:05:45.77171152Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:05:45Z" level=info msg="Snapshot: 10.40.0.24:10000 c-9cfdm0-da261550 UserCreated true Created at 2020-12-02T13:05:45Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:05:45.772864454Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:05:45Z" level=info msg="Snapshot: 10.32.0.19:10375 c-9cfdm0-da261550 UserCreated true Created at 2020-12-02T13:05:45Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:04.369097078Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:06:04Z" level=info msg="Snapshot: 10.40.0.24:10000 c-9cfdm0-aa46c5df UserCreated true Created at 2020-12-02T13:06:04Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:04.370462137Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:06:04Z" level=info msg="Snapshot: 10.32.0.19:10375 c-9cfdm0-aa46c5df UserCreated true Created at 2020-12-02T13:06:04Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:39.420198746Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-e-47a40e9f] time="2020-12-02T13:06:39Z" level=info msg="Snapshot: 10.32.0.19:10375 c-9cfdm0-573d6d03 UserCreated true Created at 2020-12-02T13:06:39Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:39.420225428Z time="2020-12-02T13:06:39Z" level=info msg="Snapshot: 10.40.0.24:10000 c-9cfdm0-573d6d03 UserCreated true Created at 2020-12-02T13:06:39Z, Labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
```
```
2020-12-02T13:05:34.464717294Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-d2fb24e2] time="2020-12-02T13:05:34Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-ea8d222d] volume, user created true, created time 2020-12-02T13:05:34Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:05:45.777218159Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-d2fb24e2] time="2020-12-02T13:05:45Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-da261550] volume, user created true, created time 2020-12-02T13:05:45Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:04.372124102Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-d2fb24e2] time="2020-12-02T13:06:04Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-aa46c5df] volume, user created true, created time 2020-12-02T13:06:04Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:39.422880127Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-d2fb24e2] time="2020-12-02T13:06:39Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-573d6d03] volume, user created true, created time 2020-12-02T13:06:39Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
```
```
2020-12-02T13:05:34.46468566Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T13:05:34Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-ea8d222d] volume, user created true, created time 2020-12-02T13:05:34Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:05:45.773948585Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T13:05:45Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-da261550] volume, user created true, created time 2020-12-02T13:05:45Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:04.371410999Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T13:06:04Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-aa46c5df] volume, user created true, created time 2020-12-02T13:06:04Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
2020-12-02T13:06:39.423024682Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T13:06:39Z" level=info msg="Replica server starts to snapshot [c-9cfdm0-573d6d03] volume, user created true, created time 2020-12-02T13:06:39Z, labels map[RecurringJob:c-9cfdm0 app:orch-ubb-processing]"
```
2. I saw there is a snapshot cleanup around `"2020-12-02T12:48:18Z"`. Since it was done within 1 minute and the snapshot creation error was reported at `2020-12-02T13:05:57Z` (which is 18 minutes later than the cleanup timestamp), it's unlikely that this cleanup is the culprit.
```
2020-12-02T12:48:17.414879716Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:17Z" level=info msg="Marking disk bkp2-1-350e8661 as removed"
2020-12-02T12:48:18.201484566Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:18Z" level=info msg="Prepare removing disk: bkp2-1-350e8661"
2020-12-02T12:48:18.203005636Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:18Z" level=info msg="Coalescing volume-snap-bkp2-1-0da48f0c.img to volume-snap-bkp2-1-350e8661.img"
2020-12-02T12:48:18.205478016Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:18Z" level=info msg="Replace volume-snap-bkp2-1-0da48f0c.img with volume-snap-bkp2-1-350e8661.img"
2020-12-02T12:48:18.207838493Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:18Z" level=info msg="Replacing disk volume-snap-bkp2-1-0da48f0c.img with volume-snap-bkp2-1-350e8661.img"
2020-12-02T12:48:18.207851657Z time="2020-12-02T12:48:18Z" level=info msg="Old file volume-snap-bkp2-1-0da48f0c.img exists, deleting"
2020-12-02T12:48:18.207855641Z time="2020-12-02T12:48:18Z" level=info msg="Done replacing volume-snap-bkp2-1-0da48f0c.img with volume-snap-bkp2-1-350e8661.img"
2020-12-02T12:48:22.048811057Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:22Z" level=info msg="Marking disk bkp2-1-0da48f0c as removed"
2020-12-02T12:48:23.132836592Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:23Z" level=info msg="Prepare removing disk: bkp2-1-0da48f0c"
2020-12-02T12:48:23.134863248Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:23Z" level=info msg="Coalescing volume-snap-bkp2-1-69995024.img to volume-snap-bkp2-1-0da48f0c.img"
2020-12-02T12:48:23.73194059Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:23Z" level=info msg="Replace volume-snap-bkp2-1-69995024.img with volume-snap-bkp2-1-0da48f0c.img"
2020-12-02T12:48:23.733520822Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:23Z" level=info msg="Replacing disk volume-snap-bkp2-1-69995024.img with volume-snap-bkp2-1-0da48f0c.img"
2020-12-02T12:48:23.733536639Z time="2020-12-02T12:48:23Z" level=info msg="Old file volume-snap-bkp2-1-69995024.img exists, deleting"
2020-12-02T12:48:23.735548884Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:23Z" level=info msg="Done replacing volume-snap-bkp2-1-69995024.img with volume-snap-bkp2-1-0da48f0c.img"
2020-12-02T12:48:31.308918755Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:31Z" level=info msg="Marking disk bkp2-1-69995024 as removed"
2020-12-02T12:48:32.296064395Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:32Z" level=info msg="Prepare removing disk: bkp2-1-69995024"
2020-12-02T12:48:32.296097245Z time="2020-12-02T12:48:32Z" level=info msg="Coalescing volume-snap-bkp2-1-e4a7577e.img to volume-snap-bkp2-1-69995024.img"
2020-12-02T12:48:32.298078847Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:32Z" level=info msg="Replace volume-snap-bkp2-1-e4a7577e.img with volume-snap-bkp2-1-69995024.img"
2020-12-02T12:48:32.299443544Z [pvc-c0acdcbc-f258-4764-8ef5-68214842df74-r-488c83c8] time="2020-12-02T12:48:32Z" level=info msg="Replacing disk volume-snap-bkp2-1-e4a7577e.img with volume-snap-bkp2-1-69995024.img"
```
3. Since you restarted the longhorn manager DaemonSet, all the logs before `2020-12-04T09:47:43Z` is lost. Then I cannot find any snapshot creation timeout error for volume `pvc-c0acdcbc-f258-4764-8ef5-68214842df74` in longhorn manager pods. Also, I didn't find any other volumes encountering the snapshot creation timeout error in the support bundle. Since you mentioned `it didn't work, same behavior`, can you provide more details for the latest behavior? e.g., volume name, and when the issue happens.

**Comment by FCarvMobil** [comment]
Guys, I'm truly sorry about this late answer, those last days were really busy and demanding. 

As the version 1.1.0 is available now I ask you what you prefer for me to do; if I provide you more details and a new support bundle from my current version (1.0.2) or to install the new version 1.1.0 and check if this backup issue changes or solves itself.

Again, thanks for your attention!

**Comment by shuo-wu** [comment]
Feel free to update to the latest version. If possible, please generating the support bundle before applying any workaround once you encounter this issue again.

**Comment by FCarvMobil** [comment]
Hi guys. First of all, Happy New Year!

I'd upgraded yesterday the longhorn installation to version 1.1.0 - it went ok but I was spooked for a while as the UI didn't show volumes, nodes or even the gauges; just to find out that my link to the UI was wrong.

About the issue with the backups, I think it is solved. The volume analyzed by @shuo-wu completed its backup successfully as a few others also.
I'll setup again the backup schedules for all remaining affected workloads and check again tomorrow.

A last comment: I didn't find at the Settings Reference a topic for the '**replica-replenishment-wait-interval**' setting. https://longhorn.io/docs/1.1.0/references/settings/ 

Thanks for your attention
and best regards.

**Comment by shuo-wu** [comment]
We will update the doc for the new settings:https://github.com/longhorn/longhorn/issues/2153 
Thank you for pointing this out!

**Comment by shuo-wu** [comment]
And if you can reproduce the issue later, feel free to re-open this issue

**Comment by FCarvMobil** [comment]
Sorry guys, a few PVCs still had the issue.
Tell me what you want me to do, to try something or to send you an updated support bundle.

The PVCs that failed.
pvc-8a815c0b-13a2-43e0-a433-3b22b3277344
pvc-f19d6fc3-d2b3-4e01-8aa8-a834626f3f34
pvc-f074f9f0-020d-40dc-8d94-7d9f670484ed - it was working then stopped
pvc-43da6f1c-29b5-4120-9d64-58778f8f3b20 - this PVC was created a week ago

Again, thanks.

**Comment by shuo-wu** [comment]
You mean this backup issue still? Can you generate the support bundle and send it to <longhorn-support-bundle@rancher.com>?

**Comment by FCarvMobil** [comment]
Yes, the same issue. I'm sending the support bundle right now.

**Comment by shuo-wu** [comment]
Here are the problematic volumes I found in the new support bundle:

1. pvc-8a815c0b-13a2-43e0-a433-3b22b3277344
```
2021-01-05T08:46:07.112252931Z 10.44.0.0 - - [05/Jan/2021:08:45:07 +0000] "POST /v1/volumes/pvc-8a815c0b-13a2-43e0-a433-3b22b3277344?action=snapshotCreate HTTP/1.1" 500 521 "" "Go-http-client/1.1"
2021-01-05T08:46:07.112254784Z time="2021-01-05T08:46:07Z" level=warning msg="HTTP handling error fail to create snapshot: error creating snapshot 'c-koiugo-3c9ee79c': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10006 snapshot create --label RecurringJob=c-koiugo --label app=openldap-telustelemetry-v03-data c-koiugo-3c9ee79c], output , stderr, , error <nil>"
2021-01-05T08:46:07.112308964Z time="2021-01-05T08:46:07Z" level=error msg="Error in request: fail to create snapshot: error creating snapshot 'c-koiugo-3c9ee79c': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10006 snapshot create --label RecurringJob=c-koiugo --label app=openldap-telustelemetry-v03-data c-koiugo-3c9ee79c], output , stderr, , error <nil>"
```
```
2021-01-05T08:46:57.17037788Z [pvc-8a815c0b-13a2-43e0-a433-3b22b3277344-e-69bc437a] time="2021-01-05T08:46:57Z" level=info msg="Snapshot: 10.40.0.23:10150 c-koiugo-3c9ee79c UserCreated true Created at 2021-01-05T08:46:57Z, Labels map[RecurringJob:c-koiugo app:openldap-telustelemetry-v03-data]"
2021-01-05T08:46:57.170399588Z time="2021-01-05T08:46:57Z" level=info msg="Snapshot: 10.32.0.39:10135 c-koiugo-3c9ee79c UserCreated true Created at 2021-01-05T08:46:57Z, Labels map[RecurringJob:c-koiugo app:openldap-telustelemetry-v03-data]"
```
```
2021-01-05T08:46:57.175754546Z [pvc-8a815c0b-13a2-43e0-a433-3b22b3277344-r-f2ecdf9e] time="2021-01-05T08:46:57Z" level=info msg="Replica server starts to snapshot [c-koiugo-3c9ee79c] volume, user created true, created time 2021-01-05T08:46:57Z, labels map[RecurringJob:c-koiugo app:openldap-telustelemetry-v03-data]"
```

2. pvc-f19d6fc3-d2b3-4e01-8aa8-a834626f3f34
```
2021-01-05T08:47:13.206868213Z [pvc-f19d6fc3-d2b3-4e01-8aa8-a834626f3f34-e-1b40ac27] time="2021-01-05T08:47:13Z" level=info msg="Snapshot: 10.46.0.12:10120 b2r1b-c629a402 UserCreated true Created at 2021-01-05T08:47:13Z, Labels map[RecurringJob:b2r1b app:openldap-telustelemetry-v03-config]"
2021-01-05T08:47:13.206890163Z time="2021-01-05T08:47:13Z" level=info msg="Snapshot: 10.32.0.39:10180 b2r1b-c629a402 UserCreated true Created at 2021-01-05T08:47:13Z, Labels map[RecurringJob:b2r1b app:openldap-telustelemetry-v03-config]"
```
```
2021-01-05T08:46:09.39858946Z time="2021-01-05T08:46:09Z" level=warning msg="HTTP handling error fail to create snapshot: error creating snapshot 'b2r1b-c629a402': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10004 snapshot create --label RecurringJob=b2r1b --label app=openldap-telustelemetry-v03-config b2r1b-c629a402], output , stderr, , error <nil>"
2021-01-05T08:46:09.398624584Z time="2021-01-05T08:46:09Z" level=error msg="Error in request: fail to create snapshot: error creating snapshot 'b2r1b-c629a402': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10004 snapshot create --label RecurringJob=b2r1b --label app=openldap-telustelemetry-v03-config b2r1b-c629a402], output , stderr, , error <nil>"
```

3. pvc-a70725b3-1fc9-4286-abe9-8904b036e6e5
```
2021-01-05T03:31:58.035222186Z [pvc-a70725b3-1fc9-4286-abe9-8904b036e6e5-e-c7a598c2] time="2021-01-05T03:31:58Z" level=info msg="Snapshot: 10.46.0.12:10210 c-9lloy7-c8f0cd41 UserCreated true Created at 2021-01-05T03:31:58Z, Labels map[RecurringJob:c-9lloy7 app:orch-ngnra]"
2021-01-05T03:31:58.03681542Z [pvc-a70725b3-1fc9-4286-abe9-8904b036e6e5-e-c7a598c2] time="2021-01-05T03:31:58Z" level=info msg="Snapshot: 10.40.0.23:10210 c-9lloy7-c8f0cd41 UserCreated true Created at 2021-01-05T03:31:58Z, Labels map[RecurringJob:c-9lloy7 app:orch-ngnra]"
```
```
2021-01-05T03:31:06.821023183Z time="2021-01-05T03:31:06Z" level=warning msg="HTTP handling error fail to create snapshot: error creating snapshot 'c-9lloy7-c8f0cd41': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10008 snapshot create --label RecurringJob=c-9lloy7 --label app=orch-ngnra c-9lloy7-c8f0cd41], output , stderr, , error <nil>"
2021-01-05T03:31:06.821061887Z time="2021-01-05T03:31:06Z" level=error msg="Error in request: fail to create snapshot: error creating snapshot 'c-9lloy7-c8f0cd41': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10008 snapshot create --label RecurringJob=c-9lloy7 --label app=orch-ngnra c-9lloy7-c8f0cd41], output , stderr, , error <nil>"
```

4. pvc-e477eda9-eda7-4974-83e7-96d467fa6091
```
2021-01-05T03:32:06.212502571Z [pvc-e477eda9-eda7-4974-83e7-96d467fa6091-e-85a5d5fb] time="2021-01-05T03:32:06Z" level=info msg="Snapshot: 10.46.0.12:10075 bkp2-r2-f0ac67e2 UserCreated true Created at 2021-01-05T03:32:06Z, Labels map[RecurringJob:bkp2-r2 app:orch-mongodb]"
2021-01-05T03:32:06.218017219Z [pvc-e477eda9-eda7-4974-83e7-96d467fa6091-e-85a5d5fb] time="2021-01-05T03:32:06Z" level=info msg="Snapshot: 10.32.0.39:10090 bkp2-r2-f0ac67e2 UserCreated true Created at 2021-01-05T03:32:06Z, Labels map[RecurringJob:bkp2-r2 app:orch-mongodb]"
```
```
2021-01-05T03:31:07.943113624Z time="2021-01-05T03:31:07Z" level=warning msg="HTTP handling error fail to create snapshot: error creating snapshot 'bkp2-r2-f0ac67e2': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10003 snapshot create --label RecurringJob=bkp2-r2 --label app=orch-mongodb bkp2-r2-f0ac67e2], output , stderr, , error <nil>"
2021-01-05T03:31:07.943140743Z time="2021-01-05T03:31:07Z" level=error msg="Error in request: fail to create snapshot: error creating snapshot 'bkp2-r2-f0ac67e2': Timeout executing: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.46.0.11:10003 snapshot create --label RecurringJob=bkp2-r2 --label app=orch-mongodb bkp2-r2-f0ac67e2], output , stderr, , error <nil>"
```

---

Since the log of all volumes above are similar. Let's focus on volume `pvc-8a815c0b-13a2-43e0-a433-3b22b3277344`.

Longhorn manager receives the HTTP call at `05/Jan/2021:08:45:07` and throws the timeout (1 minute) error at `2021-01-05T08:46:07`. The engine starts to do snapshot at `2021-01-05T08:46:57`. And the replicas receive the snapshot call immediately once the engine starts the snapshotting.

Hence, this next is, what blocks the engine snapshot.

First, I checked if the lock of the previous operation blocks the snapshotting. According to the engine manager log, the previous operation is rebuilding. But when the following [logs](https://github.com/longhorn/longhorn-engine/blob/b9e072eb19cfcc27894e10a8e60794c66ca918f8/pkg/controller/rebuild.go#L123) are shown, the rebuilding is almost done. It's unlikely that this rebuilding blocks the snapshotting:
```
2021-01-03T16:02:16.739895792Z [pvc-8a815c0b-13a2-43e0-a433-3b22b3277344-e-69bc437a] time="2021-01-03T16:02:16Z" level=info msg="Set backend tcp://10.40.0.23:10150 revision counter to 333150"
2021-01-03T16:02:16.739920127Z time="2021-01-03T16:02:16Z" level=info msg="WO replica tcp://10.40.0.23:10150's chain verified, update mode to RW"
2021-01-03T16:02:16.744631618Z [pvc-8a815c0b-13a2-43e0-a433-3b22b3277344-e-69bc437a] time="2021-01-03T16:02:16Z" level=info msg="Set replica tcp://10.40.0.23:10150 to mode RW"
```

Then I guess there may be some blocking operations/functions inside the snapshot function. Right now the only suspects I can find is [the sync function](https://github.com/longhorn/longhorn-engine/blob/b9e072eb19cfcc27894e10a8e60794c66ca918f8/pkg/controller/control.go#L175). I will check if there are any other clues.

**Comment by shuo-wu** [comment]
And I just found there was a similar bug report: https://github.com/longhorn/longhorn/issues/2068

**Comment by shuo-wu** [comment]
Can you provide the environment/config of your cluster? The CPU limitation or the disk performance may cause an unexpected delay of the snapshotting, too. Since there are 37 volumes running in your cluster, the CPU resource/disk performance may be exhausted during the snapshotting.

Here is the checklist of the environment:

**Environment:**
 - Longhorn version:
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Comment by FCarvMobil** [comment]
Sure!

> **Environment:**
> 
> * Longhorn version: _v.1.1.0_
> * Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
>   _It's the standard distro (we got all binaries directly from Google), version 1.17.0, over DockerCE._
>   
>   * Number of management node in the cluster: 4
>   * Number of worker node in the cluster: 4
>   _The cluster had 4 nodes without segregation on control-plane and workers. It's an old issue with this customers's IT area. I know, isn't even an odd number now._ 
>
> * Node config
>   
>   * OS type and version: _Oracle Linux Server 7.6~7.9_
>   * CPU per node: _12~16_
>   * Memory per node: _64~96 GB_
>   * Disk type(e.g. SSD/NVMe): _probably SSD (as it is at VMware)_
>   * Network bandwidth between the nodes: _10 Gbps networks, **almost** this on iperf3 measurements_
> * Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
> _All 4 nodes are VMware VMs. We don't have access to the low-level management on these VMs_.

This cluster suffers from restrictions by the way the customer run its IT resources. This is pretty much why the cluster is currently not 100% symmetrical on nodes and resources - but it is a story for another thread.
Has been a fight between us and the users over the IT area, restrictions on architecture and services (like the proxy thing), and obviously budgets.

Thanks again, best regards.

**Comment by shuo-wu** [comment]
1. Great, the nodes in your cluster are pretty powerful. Notice that the memory size is pretty big, and typically the cache/buffer size (that will used in the volume i/o) is propotionate to the total memory size, I am not sure what the buffer/cache size is. Maybe you can check and tune it to avoid the potential long sync period.
2. Just in case, can you use `fio` or `dd` to do a simple benchmark for your disk?
3. According to the support bundle, the snapshot will be created finally with a delay even if Longhorn reports a timeout error. Can you try the following test if possible? If there is no timeout in step3, then the sync function may be the culprit and you may need to decrease the related buffer/cache size.
    1. Create a 1Gi volume and attach it to the node on which the above problematic volumes are. You can do it via UI and there is no need to mount it somewhere.
    2. Manually create one snapshot via UI and wait for the snapshot creation even if there is a timeout error.
    3. (Stop data writing in cluster wide before the test is done if possible.) Immediately create one more snapshot after the 1st snapshot created.

**Comment by FCarvMobil** [comment]
Hi @shuo-wu , hope you're good. Sorry on this late answer, really busy after one team member departed early this month.

1. The buffer/cache is at the OS standard, I didn't make any adjustments.
2. I've done with dd. Results at the attachment 'longhorn-issue2029-dd-test.txt' with a few names redacted, references maintained.
[longhorn-issue2029-dd-test.txt](https://github.com/longhorn/longhorn/files/5895143/longhorn-issue2029-dd-test.txt)

3. I've performed the steps and there's no error at all. I'd attached the log here ('longhorn-manager-issue2029-logs-volume-test.txt' with a few names redacted). 
[longhorn-manager-issue2029-logs-volume-test.txt](https://github.com/longhorn/longhorn/files/5895148/longhorn-manager-issue2029-logs-volume-test.txt)

I still have some doubts about the system-wide proxy affecting the scheduled jobs (snaps/backups). There's a way to insert a ENV var at the created pods for the snaps/backups? I'm thinking on set the 'no_proxy' ENV that prevents internal requests going to the proxy. These timeouts make me think on that.

Thanks!

**Comment by shuo-wu** [comment]
The disk performance is not bad, it won't be the cause. And based on the test result, the only possibility I can find right now is the `sync` call. 

As for the ENV setup, currently there is no APIs or settings in Longhorn to do it. Maybe you can manually update the snapshot/backup cron jobs or Longhorn workloads as the workaround. Be careful that the workloads will be restarted when you update `env`

**Comment by lucky4ever2** [comment]
I have exactly the same problem with a big Volume.

```
time="2021-02-01T13:36:45Z" level=info msg="Running recurring backup for volume pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"

time="2021-02-01T13:36:45Z" level=debug msg="Cleaned up snapshot c-mvap3z-eff9718e for pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"

time="2021-02-01T13:36:55Z" level=info msg="Handling volume detachment for volume pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"

time="2021-02-01T13:36:55Z" level=fatal msg="Error taking snapshot: failed to complete backupAndCleanup for pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d: Post \"http://longhorn-backend:9500/v1/volumes/pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d?action=snapshotBackup\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```
What do you mean by `And based on the test result, the only possibility I can find right now is the sync call.`?

**Comment by shuo-wu** [comment]
> I have exactly the same problem.
> 
> ```
> time="2021-02-01T13:36:45Z" level=info msg="Running recurring backup for volume pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"
> 
> time="2021-02-01T13:36:45Z" level=debug msg="Cleaned up snapshot c-mvap3z-eff9718e for pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"
> 
> time="2021-02-01T13:36:55Z" level=info msg="Handling volume detachment for volume pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d"
> 
> time="2021-02-01T13:36:55Z" level=fatal msg="Error taking snapshot: failed to complete backupAndCleanup for pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d: Post \"http://longhorn-backend:9500/v1/volumes/pvc-dca02b3d-8845-4e35-b4ba-7e004238d70d?action=snapshotBackup\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
> ```
> 
> What do you mean by `And based on the test result, the only possibility I can find right now is the sync call.`?

The call `snapshotBackup` contains a synced snapshot creation and an asynced backup creation. And the main blocking operation of this call is [this sync function during the snapshot creation](https://github.com/longhorn/longhorn-engine/blob/b9e072eb19cfcc27894e10a8e60794c66ca918f8/pkg/controller/control.go#L175).

**Comment by shuo-wu** [comment]
We plan to test Longhorn on high spec nodes and see if we can trigger this issue: https://github.com/longhorn/longhorn/issues/2246

**Comment by FCarvMobil** [comment]
Hi guys, any news on this?
Best regards!

**Comment by virus2016** [comment]
I have had this issue before on our test cluster. We moved to only backups and it have been perfect ever since. 

On our production clusters we have found that snapshots haven't been the most reliable especially on databases (postgres) where if data is being written at the same time as the snapshot, both snapshot and volume become corrupted. We switched to a full backup and instead of snapshot and it seems to be working great.

I would like to know the implications. Is using backups frequently every 30mins okay? What's the difference when longhorn takes a backup and snapshot?

**Comment by shuo-wu** [comment]
> I have had this issue before on our test cluster. We moved to only backups and it have been perfect ever since.
> 
> On our production clusters we have found that snapshots haven't been the most reliable especially on databases (postgres) where if data is being written at the same time as the snapshot, both snapshot and volume become corrupted. We switched to a full backup and instead of snapshot and it seems to be working great.
> 
> I would like to know the implications. Is using backups frequently every 30mins okay? What's the difference when longhorn takes a backup and snapshot?

What do you mean by `both snapshot and volume become corrupted`? To create a backup, Longhorn will create a snapshot first then do a backup based on this snapshot. Hence backup working fine but snapshot being problematic does not make sense... Since Longhorn volume itself is a block device, it doesn't understand the filesystem and the application data format. If there is part of a record data that hasn't been written into volume but the snapshot creation happens, the snapshot data may be not valid. We will improve this part in the next release: https://github.com/longhorn/longhorn/issues/2187

**Comment by virus2016** [comment]
I mean the volume stops responding in the pod and if we restart/delete it, the pod will be stuck. The volume attaches fine according to longhorn. We then use maintenance mode and revert back to a working snapshot/backup. 

Could it be that if you do a snapshot close or at the same time as the backup it could get into this state? 

We haven’t had the above issue for a while now so I don’t have a support bundle for you to look at. I maybe able to use an non critical service to see if we can replicate this specific issue for you.

**Comment by joshimoo** [comment]
A backup always creates a snapshot first, then exports that snapshots data to the final storage (s3, nfs).

**Comment by shuo-wu** [comment]
> the volume stops responding in the pod and if we restart/delete it, the pod will be stuck.

Ideally snapshotting should be done in seconds and it won't block or fail data r/w. Not sure if the cache flushing would lead to this case. Need to see if the fix I mentioned works in the next release.

**Comment by FCarvMobil** [comment]
Hello guys, just an update from me about the issue.

Starting from the assumption that the problem was in one of my cluster nodes (every volume in a pod running at this node starts to fail the backup as explained earlier) I managed to isolate the node where K8s don't schedule pods with PVCs on it.

Then, the problem 'moved' to another node... sigh.

So I'm asking if there's any news about this open issue? 

I'll more likely dump most of the Longhorn volumes for most of the workloads and start to use a shared disk approach because I cannot handle this anymore - my participation at this project and customer is also ending and the customer doesn't have anyone available to take over this 'administration' of the problem.

Thanks!

**Comment by virus2016** [comment]
Hopefully this fix will address our issues. When are we looking to get the next release of longhorn with this in it?

**Comment by shuo-wu** [comment]
@FCarvMobil I plan to replace `sync` with `fsfreeze` for the snapshot creation. Then the following backup creation won't be blocked if `sync` is the root cause.

@virus2016 The fix will be in the next release.

**Comment by innobead** [comment]
Closing. #2187 was introduced in 1.1.1 already, so please give it a try to see if you still encounter this issue. Feel free to reopen. Thanks.

**Comment by ChipWolf** [comment]
> Closing. #2187 was introduced in 1.1.1 already, so please give it a try to see if you still encounter this issue. Feel free to reopen. Thanks.

@innobead re-open as that was reverted?
