### ISSUE TITLE
[BUG] orphaned pod pod_id found, but error not a directory occurred when trying to remove the volumes dir

### ISSUE THREAD

**Issue by rlex** [longhorn/longhorn#3207]
**Describe the bug**
After unclean node shutdown and probably some other cases, kubelet fails to remove orphaned pod with longhorn PVC

**To Reproduce**
1) Deploy k3s
2) Deploy longhorn
3) Deploy pod with longhorn volume
4) crash node with pod running / kill k3s
5) Observe the logs

**Expected behavior**
No log spam should appear

**Log**
```
k3s[471]: E1102 15:11:01.933125     471 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"5a5fd1bf-bc3c-4600-88d3-321701d3d95a\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=2
```

**Environment:**
 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster:3
   - Number of worker node in the cluster:4

**Additional context**
I'm not quite sure if this kubelet or longhorn issue. Issue itself is caused due to how kubelet manages orphaned pods cleanup - looks like it calls rmdir and if something is inside said dir it fails to drop directory. In case of longhorn-provisioned volumes, inability to cleanup orphaned pods directories is caused by 
```
vol_data.json
```
file, in my case containing
```
root@master-1:~# cat /var/lib/kubelet/pods/47a9ab25-68e9-4c8a-ab29-a3b3a0500799/volumes/kubernetes.io~csi/pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a/vol_data.json
{"attachmentID":"csi-7b27560c7ac7e905a2f097d3caef3b16ad78e7e138b1b4c6d5c427a4066e9729","driverName":"driver.longhorn.io","nodeName":"master-1","specVolID":"pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a","volumeHandle":"pvc-5232ca8d-b13f-42eb-8088-ec08cee51a7a","volumeLifecycleMode":"Persistent"}
```

Removing that dangling file allows kubelet to proceed with orphaned pod cleanup.

There is also this https://github.com/longhorn/longhorn/issues/3080 ticket but seems those are caused by different cases.

**Comment by rlex** [comment]
Additionally: https://github.com/kubernetes/kubernetes/issues/60987#issuecomment-415370444

**Comment by derekbit** [comment]
@rlex , what's your k3s version?

**Comment by rlex** [comment]
v1.22.2+k3s2

**Comment by derekbit** [comment]
@rlex 
I cannot reproduce it in my environment.

Could you please help to provide the following information for narrowing down the problem and further analysis?
- What's your longhorn configuration? number of replicas? Are some nodes unscheduable?
- Pod and PVC yaml files for reproduce
- In your step 4, after the worker nodes crashed, did it re-join to the cluster?
- In your step 5, is the log on the crashed node or other node?
- Provide the log with the above error messages

**Comment by rlex** [comment]
ATM i'm cleaned all my nodes from leftover files, so i can't give you exact configuration.
I used default storageClass with 3 replicas. All nodes are schedulable.
Node with attached PV crashed (kernel panic, probably unrelated to longhorn)
Yes, node rejoined cluster, but pod was already rescheduled and recreated at different node. Log was on crashed node.
I can try digging around in my logs, maybe i can find that error message again.

**Comment by derekbit** [comment]
@rlex 
Here's my step trying to reproduce, but I can't reproduce with multiple trials.
If there is anything I missed or any clue, please let me know, thank you.

1. Deploy k3s (1 masetr + 4 workers)
2. Deploy longhorn with 3 replicas
3. Deploy deployment with longhorn volume
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-test
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: volume-test
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      restartPolicy: Always
      containers:
      - name: volume-test
        image: ubuntu:20.04
        command:
          - "sleep"
          - "604800"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: volv
          mountPath: /data
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc
```

4. kill worker not where pod is running by `systemctl stop k3s-agent.service` 
5. After the node becomes NotReady, re-join the worker to the cluster by `systemctl start k3s-agent.service` 
6. Check the logs

**Comment by rlex** [comment]
Can you try non-clean shutdown, simulating power outage or something like this? Killing VM? I think this is what caused leftover files, but i'm not sure.

**Comment by derekbit** [comment]
@rlex 

Sorry for being late reply. I can reproduce the issue by increasing the power outage period.

I noticed the error messages in the reboot node' kubelet log. The root cause is that the connection to CSI driver was broken, so the remove of vol_data.json in UnmountVolume.TearDown cannot be executed and lead to the Rmdir failure of the old volume mountpoint.

So, there were lots of error messages in the kubelet log.
```
Nov 21 15:48:02 ku60-worker2 k3s[888]: E1121 15:48:02.200715     888 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"7c718603-7246-49e4-86df-c77a4a8fe868\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=1
Nov 21 15:48:02 ku60-worker2 k3s[888]: I1121 15:48:02.200758     888 kubelet_volumes.go:247] "Orphan pod" err="orphaned pod \"7c718603-7246-49e4-86df-c77a4a8fe868\" found, but error not a directory occurred when trying to remove the volumes dir"
```

You don't need delete the dangling vol_data.json in the old mountpoint directory. After restart of the longhorn-csi plugin automatically and waiting for several minutes, the pod with a new volume mountpoint will be at Running state again.

The bug is related to the kubelet logic and does not impact the usage of Longhorn.

Related to https://github.com/kubernetes/kubernetes/issues/105536

**Comment by innobead** [comment]
cc @joshimoo

**Comment by shuo-wu** [comment]
@derekbit Does this mean that asking Longhorn to start the CSI plugin automatically after kubelet/node restart would help fix this issue?

**Comment by derekbit** [comment]
@shuo-wu 
Yes. The CSI plugin can restart automatically after the restart of the node and kubelet now, so we don't need to do any change.
The influence of vol_data.json in old volume on the restart node is the repeated error log messages. It should be fixed in kubelet.

**Comment by agustinvinao** [comment]
Hi,

I'm getting the same issue, in one of my nodes I'm seeing:
```
Dec 21 14:05:15 favaloro k3s[574]: E1221 14:05:15.034587     574 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"020dade9-54be-4330-8a3e-6bcea2901b43\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=7
```

After restarting the node, or even the plugin, the error never goes away. 

Can I do anything to solve it?
K3s v1.22.4

**Comment by rlex** [comment]
for the time being, you need to cleanup it manually. 
Go to /var/lib/kubelet/pods/$pod_id/volumes/kubernetes.io~csi/pvc_$pvc_id/ and delete vol_data.json after making sure this is not "live" volume. 

As Derek said, this is not longhorn bug, that's how kubelet is handling folder cleanup (calling rmdir will always fail if this directory contains anything)

**Comment by agustinvinao** [comment]
@rlex how can I know a volume is `not "live" volume.` ?

**Comment by rlex** [comment]
>@rlex how can I know a volume is not "live" volume. ?

I think if it attempts to cleanup it's not live, but you can check volume details in longhorn web ui. If it's not scheduled on that node, it should be safe to delete.

**Comment by badnetmask** [comment]
I can confirm this bug running v1.2.3. I spotted it on my environment after my k3s master was powered down by mistake, while the nodes were still were running.

k3s[797]: E0123 21:15:24.559660     797 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"7316f31a-e2cb-4d92-8667-46ba6b610228\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=1

After removing the vol_data.json file manually, the system recovered by itself.

k3s[797]: I0123 21:15:26.597356     797 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=7316f31a-e2cb-4d92-8667-46ba6b610228 path="/var/lib/kubelet/pods/7316f31a-e2cb-4d92-8667-46ba6b610228/volumes"

**Comment by innobead** [comment]
> Two options:
> 
> "You don't need to delete the dangling vol_data.json in the old mountpoint directory by manual. After restart of the longhorn-csi plugin automatically and waiting for several minutes, the pod with a new volume mountpoint will be at Running state again." - in case crashed replica is rescheduled on same node.
> 
> But If replica has been rescheduled to different node and you have dangling vol_data.json you need to go to `var/lib/kubelet/pods/$pod_id/volumes/kubernetes.io~csi/pvc_$pvc_id/` and delete vol_data.json after making sure this is not "live" volume.
> 
> As Derek said, this is not longhorn bug, that's how kubelet is handling folder cleanup (calling rmdir will always fail if this directory contains anything)

@weizhe0422 could you help with this knowledge base? please check with @derekbit if having any questions.

**Comment by rpardini** [comment]
Interesting: nodes affected by this are marked `DiskPressure`, at least in k8s 1.24, even if there is no actual disk pressure at all.
Cleaning the `vol_data.json` for the affected orphaned pods clears it.

**Comment by migs35323** [comment]
I am getting this issue in a k3s v1.24.4 cluster with longhorn 1.3.2
upgraded to k3s 1.24.9 still having the same issue:
journalctl -u k3s-agent --follow shows every second the message: 
524 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"POD_ID\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=2
if i rm -rf the problematic volume it seems i am playing wak a mole, another pod from another app shows this error
longhorn seems to be fine and the cluster doesnt report any issues, no disk pressure or else..

**Comment by alexnederlof** [comment]
I ended up using this script (not I'm not a longhorn dev, I cannot guarantee this is safe)

```bash
while true ; do
for o in $(tail /var/log/syslog | grep -o  -E 'orphaned pod \\"((\w|-)+)\\' | cut -d" " -f3 | grep -oE '(\w|-)+' | uniq); do
	p="/var/lib/kubelet/pods/$o/volumes/*"
	if [ -d "$p" ] ; then
	  echo "Removing $o"
	  rm -rf "$p"
	fi
done
sleep 2
done
```

**Comment by Dunge** [comment]
Also seeing this error on microk8s 1.26.4 and Longhorn 1.4.1 it was flooding my kubelite syslogs.

No idea how it started, I believe it happened after I rebooted the nodes.
Deleted one of these "orphaned pod" and another shows up instead. Ended up having to delete about 15. On all nodes.

Would be interesting to have a more robust solution than running a script that delete files manually. Why does this happen, how can we prevent it from happening?

**Comment by webees** [comment]
I got this error after a forced server restart!

Longhorn 1.4.2

**Comment by larssb** [comment]
Have you tried updating to v1.27 or v1.28 of Kubernetes? To see if that fixes it @migs35323 ?

**Comment by migs35323** [comment]
> Have you tried updating to v1.27 or v1.28 of Kubernetes? To see if that fixes it @migs35323 ?

We are still at 1.25, i would rather to use the script as a bandage for now...
Cluster has production stuff and has dependencies like longhorn and rancher which need to be upgraded first...
Can't afford surprises and have whole cluster down at this time...
reminds me of this image, however in my case instead of etcd it's longhorn
https://github.com/etcd-io/etcd/blob/main/logos/etcd-xkcd-2347.png

**Comment by larssb** [comment]
Reach out on Rancher Slack - find me as @lbingchong ...

**Comment by migs35323** [comment]
managed to adapt the script, here's my take, feel free to improve:

i tried to target the problematic file itself, so kubelet takes care of the rest
`while true ; do
for o in $(journalctl -u k3s-agent -n 10 -o cat | grep -o  -E 'orphaned pod \\"((\w|-)+)\\' | cut -d" " -f3 | grep -oE '(\w|-)+' | uniq); do
	p="/var/lib/kubelet/pods/$o/volumes/kubernetes.io~csi/*/vol_data.json"
	if [ -f $p ] ; then
    echo "hello"
	  echo "Removing $o"
	  rm -rfi $p
	fi
  echo "goodbye"
done
sleep 2
done`

**Comment by audiophonicz** [comment]
I've been trying to get this script to work for my setup using crontab for a while now (my coding isnt the best) that wouldnt infinite loop but still loop thru to get all of the orphaned pods before exiting. I think I finally got it. Sharing for anyone that wants to schedule this rather than have it constantly running.

@migs35323 I like your "let kubelet handle itself" approach but your if statement was throwing "binary operator expected" errors for me when a pod had >1 pvc. I had to change it to look at a directory and then appended the file to delete. 

```
while true ; do
for o in $(journalctl -n 10 -o cat | grep -o  -E 'orphaned pod \\"((\w|-)+)\\' | cut -d" " -f3 | grep -oE '(\w|-)+' | uniq); do
  p="/var/lib/kubelet/pods/$o/volumes"
  if [ -d $p ] ; then
    echo "Orphaned Pod $o Found"
    echo "Removing $p/kubernetes.io~csi/"*"/vol_data.json"
    rm -rf "$p/kubernetes.io~csi/"*"/vol_data.json"
    loop=1
    echo "$p/kubernetes.io~csi/"*"/vol_data.json Removed"
    echo "Rechecking"
  else
    echo "No Orphaned Pods Found"
    loop=2
  fi
done
if [ $loop = 1 ] ; then
  sleep 2
else
  echo "Exiting"
  break
fi
done
```

If anyone has suggestions to make this more efficient, Im all ears.

**Comment by Dunge** [comment]
I am still seeing this with k8s 1.31 and longhorn 1.6.0.

Not exactly the same message (no mention of orphaned pod)

>microk8s.daemon-kubelite[2239374]: E1203 21:46:50.944218 2239374 reconciler_common.go:156] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\") pod \"4428cc89-6168-4ac2-a883-28d71aa57522\" (UID: \"4428cc89-6168-4ac2-a883-28d71aa57522\") : UnmountVolume.NewUnmounter failed for volume \"pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\") pod \"4428cc89-6168-4ac2-a883-28d71aa57522\" (UID: \"4428cc89-6168-4ac2-a883-28d71aa57522\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/mount]: kubernetes.io/csi: failed to open volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/vol_data.json]: open /var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a\") pod \"4428cc89-6168-4ac2-a883-28d71aa57522\" (UID: \"4428cc89-6168-4ac2-a883-28d71aa57522\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/mount]: kubernetes.io/csi: failed to open volume data file [/var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/vol_data.json]: open /var/snap/microk8s/common/var/lib/kubelet/pods/4428cc89-6168-4ac2-a883-28d71aa57522/volumes/kubernetes.io~csi/pvc-03d8d1f7-b71b-4c58-8d7a-581a4a9aad5a/vol_data.json: no such file or directory"

Pod get stuck in "terminating" state and there's no way to fix it. Removing the volume directory doesn't seem to work anymore.

Would updating to longhorn latest help?

How can I fix this manually?
