### ISSUE TITLE
longhorn-manager CrashLoopBackOff

### ISSUE THREAD

**Issue by zhuw0312** [longhorn/longhorn#4258]
## kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/deploy/longhorn.yaml
then 
longhorn-system   longhorn-manager-pfpr2                              0/1     CrashLoopBackOff   42 (3m12s ago)   3h13m
longhorn-system   longhorn-manager-xb2fb                              0/1     CrashLoopBackOff   42 (2m34s ago)   3h13m
longhorn-system   longhorn-manager-zzxhf                              0/1     CrashLoopBackOff   42 (3m8s ago)    3h13m

## Environment

 - Longhorn version: 1.3.0
 - Kubernetes version: 1.24.2
 - Node config
   - OS type and version: centos7
   - CPU per node: 4c
   - Memory per node: 8g
   - Disk type: hdd
  
[root@wf-dev-mid-k8s-m longhorn]# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.

**Comment by zhuw0312** [comment]
```
[root@wf-dev-mid-k8s-m_ ~]# kubectl logs -n longhorn-system longhorn-manager-zzxhf 
Defaulted container "longhorn-manager" out of: longhorn-manager, wait-longhorn-admission-webhook (init)
W0720 12:40:52.358332       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-07-20T12:40:52Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access /var/lib/rancher/longhorn/engine-binaries/*: No such file or directory\n, error exit status 2"
time="2022-07-20T12:40:52Z" level=info msg="Skip the leader election for the upgrade since the current Longhorn system is already up to date"
W0720 12:40:52.415187       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0720 12:40:52.423655       1 shared_informer.go:240] Waiting for caches to sync for longhorn datastore
W0720 12:40:52.429056       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0720 12:40:52.430539       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0720 12:40:52.440592       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0720 12:40:52.441571       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
E0720 12:40:52.444168       1 kubernetes_node_controller.go:227] couldn't get kubernetes node wf-dev-mid-k8s-n2: node "wf-dev-mid-k8s-n2" not found 
I0720 12:40:52.524150       1 shared_informer.go:247] Caches are synced for longhorn datastore 
W0720 12:40:52.524376       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Backing Image controller"
I0720 12:40:52.524807       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing images
I0720 12:40:52.524848       1 shared_informer.go:247] Caches are synced for longhorn backing images 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Orphan controller" controller=longhorn-orphan node=wf-dev-mid-k8s-n2
I0720 12:40:52.524953       1 shared_informer.go:240] Waiting for caches to sync for longhorn-orphan
I0720 12:40:52.524977       1 shared_informer.go:247] Caches are synced for longhorn-orphan 
time="2022-07-20T12:40:52Z" level=info msg="Starting Longhorn backing image manager controller"
I0720 12:40:52.525115       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image manager
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Kubernetes node controller"
I0720 12:40:52.525136       1 shared_informer.go:240] Waiting for caches to sync for longhorn kubernetes node
I0720 12:40:52.525145       1 shared_informer.go:247] Caches are synced for longhorn kubernetes node 
I0720 12:40:52.525145       1 shared_informer.go:247] Caches are synced for longhorn backing image manager 
time="2022-07-20T12:40:52Z" level=info msg="Starting Longhorn Snapshot Controller" controller=longhorn-snapshot node=wf-dev-mid-k8s-n2
I0720 12:40:52.525223       1 shared_informer.go:240] Waiting for caches to sync for longhorn-snapshot
I0720 12:40:52.525231       1 shared_informer.go:247] Caches are synced for longhorn-snapshot 
time="2022-07-20T12:40:52Z" level=info msg="Starting Longhorn backing image data source controller"
I0720 12:40:52.525296       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image data source
I0720 12:40:52.525304       1 shared_informer.go:247] Caches are synced for longhorn backing image data source 
time="2022-07-20T12:40:52Z" level=info msg="Start kubernetes controller"
I0720 12:40:52.525365       1 shared_informer.go:240] Waiting for caches to sync for kubernetes
I0720 12:40:52.525373       1 shared_informer.go:247] Caches are synced for kubernetes 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Backup Target controller" controller=longhorn-backup-target node=wf-dev-mid-k8s-n2
I0720 12:40:52.525413       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-target
I0720 12:40:52.525420       1 shared_informer.go:247] Caches are synced for longhorn-backup-target 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Backup Volume controller" controller=longhorn-backup-volume node=wf-dev-mid-k8s-n2
I0720 12:40:52.525516       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-volume
I0720 12:40:52.525522       1 shared_informer.go:247] Caches are synced for longhorn-backup-volume 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Engine Image controller" controller=longhorn-engine-image node=wf-dev-mid-k8s-n2
I0720 12:40:52.525598       1 shared_informer.go:240] Waiting for caches to sync for longhorn engine images
I0720 12:40:52.525619       1 shared_informer.go:247] Caches are synced for longhorn engine images 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Backup controller" controller=longhorn-backup node=wf-dev-mid-k8s-n2
I0720 12:40:52.525696       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup
I0720 12:40:52.525705       1 shared_informer.go:247] Caches are synced for longhorn-backup 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn replica controller" controller=longhorn-replica node=wf-dev-mid-k8s-n2
I0720 12:40:52.525751       1 shared_informer.go:240] Waiting for caches to sync for longhorn replicas
I0720 12:40:52.525764       1 shared_informer.go:247] Caches are synced for longhorn replicas 
time="2022-07-20T12:40:52Z" level=info msg="Starting Longhorn Recurring Job controller"
I0720 12:40:52.525797       1 shared_informer.go:240] Waiting for caches to sync for longhorn recurring jobs
I0720 12:40:52.525805       1 shared_informer.go:247] Caches are synced for longhorn recurring jobs 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn engine controller" controller=longhorn-engine node=wf-dev-mid-k8s-n2
I0720 12:40:52.525833       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I0720 12:40:52.525839       1 shared_informer.go:247] Caches are synced for longhorn engines 
time="2022-07-20T12:40:52Z" level=info msg=Start controller=longhorn-kubernetes-configmap-controller node=wf-dev-mid-k8s-n2
I0720 12:40:52.525905       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-configmap-controller
I0720 12:40:52.525915       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-configmap-controller 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn volume controller" controller=longhorn-volume node=wf-dev-mid-k8s-n2
I0720 12:40:52.526059       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I0720 12:40:52.526069       1 shared_informer.go:247] Caches are synced for longhorn engines 
time="2022-07-20T12:40:52Z" level=info msg="Start longhorn-kubernetes-pod-controller" controller=longhorn-kubernetes-pod node=wf-dev-mid-k8s-n2
I0720 12:40:52.526112       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-pod-controller
I0720 12:40:52.526118       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-pod-controller 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Setting controller" controller=longhorn-setting node=wf-dev-mid-k8s-n2
I0720 12:40:52.526172       1 shared_informer.go:240] Waiting for caches to sync for longhorn settings
I0720 12:40:52.526179       1 shared_informer.go:247] Caches are synced for longhorn settings 
time="2022-07-20T12:40:52Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="fail to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target-credential-secret" controller=longhorn-setting error="fail to sync setting for longhorn-system/backup-target-credential-secret: failed to sync backup target: no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn Kubernetes secret controller" controller=longhorn-kubernetes-secret-controller node=wf-dev-mid-k8s-n2
I0720 12:40:52.526618       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-secret-controller
I0720 12:40:52.526628       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-secret-controller 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn websocket controller" controller=longhorn-websocket node=wf-dev-mid-k8s-n2
I0720 12:40:52.526671       1 shared_informer.go:240] Waiting for caches to sync for longhorn websocket
time="2022-07-20T12:40:52Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=wf-dev-mid-k8s-n2
I0720 12:40:52.526690       1 shared_informer.go:247] Caches are synced for longhorn websocket 
time="2022-07-20T12:40:52Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backupstore-poll-interval" controller=longhorn-setting error="fail to sync setting for longhorn-system/backupstore-poll-interval: failed to sync backup target: no ready nodes available" node=wf-dev-mid-k8s-n2
time="2022-07-20T12:40:52Z" level=info msg="Starting Longhorn instance manager controller"
I0720 12:40:52.526927       1 shared_informer.go:240] Waiting for caches to sync for longhorn instance manager
I0720 12:40:52.526938       1 shared_informer.go:247] Caches are synced for longhorn instance manager 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn node controller"
I0720 12:40:52.526957       1 shared_informer.go:240] Waiting for caches to sync for longhorn node
I0720 12:40:52.526964       1 shared_informer.go:247] Caches are synced for longhorn node 
time="2022-07-20T12:40:52Z" level=info msg="Start Longhorn share manager controller" controller=longhorn-share-manager node=wf-dev-mid-k8s-n2
I0720 12:40:52.527011       1 shared_informer.go:240] Waiting for caches to sync for longhorn-share-manager-controller
I0720 12:40:52.527053       1 shared_informer.go:247] Caches are synced for longhorn-share-manager-controller 
time="2022-07-20T12:40:52Z" level=fatal msg="Error starting manager: create not allowed while custom resource definition is terminating"

```

**Comment by mantissahz** [comment]
Hi @zhuw0312 could you please use the newest script [environment_check.sh](https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh) to check the environment again?

**Comment by zhuw0312** [comment]
> Hi @zhuw0312 could you please use the newest script [environment_check.sh](https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh) to check the environment again?

tks very much for ur reply.when i tried again,it works.

**Comment by colliwhopper** [comment]
didnt work for me:

curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/2)...
[INFO]  All longhorn-environment-check pods are ready (2/2).
Unable to use a TTY - input is not a terminal or the right kind of file
Unable to use a TTY - input is not a terminal or the right kind of file
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.

**Comment by colliwhopper** [comment]
then longhorn install fails, manager has a crash loop backoff.

**Comment by mantissahz** [comment]
Hi @colliwhopper,
Could you please try again with this commmand `curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash`?
`Unable to use a TTY` was fixed at https://github.com/longhorn/longhorn/pull/4226

**Comment by derekbit** [comment]
@colliwhopper 
Can you also please provide the outputs of 
`kubectl -n longhorn-system logs <longhorn-manager manager>`  and 
`kubectl -n longhorn-system describe pod <longhorn-manager manager>`?
Thanks.

**Comment by xlogin** [comment]
i have the same question。

[root@vm_10_161_34_15 ~]# curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.3.2/scripts/environment_check.sh | bash
[INFO]  Required dependencies are installed.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/3)...
[INFO]  All longhorn-environment-check pods are ready (3/3).
[INFO]  Required packages are installed.
[INFO]  Cleaning up longhorn-environment-check pods...
[INFO]  Cleanup completed.

[root@vm_10_161_34_15 ~]# kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.3.2/deploy/longhorn.yaml
[root@vm_10_161_34_15 longhorn]# kubectl -n longhorn-system get pod
NAME                                           READY   STATUS             RESTARTS      AGE
engine-image-ei-a5371358-lbqwn                 1/1     Running            0             2m35s
engine-image-ei-a5371358-mbhts                 1/1     Running            0             2m35s
engine-image-ei-a5371358-xzgxf                 1/1     Running            0             2m35s
longhorn-admission-webhook-654949bc8c-t6bwl    1/1     Running            0             2m46s
longhorn-admission-webhook-654949bc8c-txdnd    1/1     Running            0             2m46s
longhorn-conversion-webhook-56544c5967-p4sfp   1/1     Running            0             2m46s
longhorn-conversion-webhook-56544c5967-z5prp   1/1     Running            0             2m46s
longhorn-driver-deployer-6698ff958f-ltgr7      1/1     Running            2 (51s ago)   2m46s
longhorn-manager-fztng                         1/1     Running            0             2m46s
longhorn-manager-npf2t                         0/1     CrashLoopBackOff   4 (56s ago)   2m46s
longhorn-manager-tzj7c                         1/1     Running            0             2m46s
longhorn-ui-5cf84d546b-grxg7                   1/1     Running            0             2m46s
[root@vm_10_161_34_15 longhorn]# kubectl -n longhorn-system logs -f longhorn-manager-npf2t
W1031 02:41:09.444886       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-10-31T02:41:09Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access /var/lib/rancher/longhorn/engine-binaries/*: No such file or directory\n, error exit status 2"
time="2022-10-31T02:41:09Z" level=info msg="Skip the leader election for the upgrade since the current Longhorn system is already up to date"
W1031 02:41:09.478682       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1031 02:41:09.482605       1 shared_informer.go:240] Waiting for caches to sync for longhorn datastore
W1031 02:41:09.488129       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1031 02:41:09.492952       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
E1031 02:41:09.494447       1 kubernetes_node_controller.go:227] couldn't get kubernetes node master-1: node "master-1" not found 
W1031 02:41:09.499355       1 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W1031 02:41:09.499511       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
I1031 02:41:09.583677       1 shared_informer.go:247] Caches are synced for longhorn datastore 
W1031 02:41:09.583814       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Backing Image controller"
I1031 02:41:09.583871       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing images
I1031 02:41:09.583883       1 shared_informer.go:247] Caches are synced for longhorn backing images 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn replica controller" controller=longhorn-replica node=master-1
I1031 02:41:09.583956       1 shared_informer.go:240] Waiting for caches to sync for longhorn replicas
I1031 02:41:09.583962       1 shared_informer.go:247] Caches are synced for longhorn replicas 
time="2022-10-31T02:41:09Z" level=info msg="Starting Longhorn instance manager controller"
I1031 02:41:09.584007       1 shared_informer.go:240] Waiting for caches to sync for longhorn instance manager
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn share manager controller" controller=longhorn-share-manager node=master-1
I1031 02:41:09.584023       1 shared_informer.go:247] Caches are synced for longhorn instance manager 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Engine Image controller" controller=longhorn-engine-image node=master-1
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn node controller"
I1031 02:41:09.584043       1 shared_informer.go:240] Waiting for caches to sync for longhorn engine images
I1031 02:41:09.584055       1 shared_informer.go:247] Caches are synced for longhorn engine images 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn engine controller" controller=longhorn-engine node=master-1
I1031 02:41:09.584065       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I1031 02:41:09.584088       1 shared_informer.go:247] Caches are synced for longhorn engines 
I1031 02:41:09.584028       1 shared_informer.go:240] Waiting for caches to sync for longhorn-share-manager-controller
I1031 02:41:09.584118       1 shared_informer.go:247] Caches are synced for longhorn-share-manager-controller 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn volume controller" controller=longhorn-volume node=master-1
I1031 02:41:09.584163       1 shared_informer.go:240] Waiting for caches to sync for longhorn engines
I1031 02:41:09.584169       1 shared_informer.go:247] Caches are synced for longhorn engines 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Orphan controller" controller=longhorn-orphan node=master-1
I1031 02:41:09.584198       1 shared_informer.go:240] Waiting for caches to sync for longhorn-orphan
I1031 02:41:09.584202       1 shared_informer.go:247] Caches are synced for longhorn-orphan 
time="2022-10-31T02:41:09Z" level=info msg="Starting Longhorn backing image manager controller"
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn websocket controller" controller=longhorn-websocket node=master-1
I1031 02:41:09.584240       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image manager
time="2022-10-31T02:41:09Z" level=info msg="Starting Longhorn Recurring Job controller"
I1031 02:41:09.584251       1 shared_informer.go:240] Waiting for caches to sync for longhorn recurring jobs
I1031 02:41:09.584252       1 shared_informer.go:247] Caches are synced for longhorn backing image manager 
I1031 02:41:09.584256       1 shared_informer.go:247] Caches are synced for longhorn recurring jobs 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Backup Target controller" controller=longhorn-backup-target node=master-1
I1031 02:41:09.584280       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-target
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Backup Volume controller" controller=longhorn-backup-volume node=master-1
I1031 02:41:09.584285       1 shared_informer.go:247] Caches are synced for longhorn-backup-target 
I1031 02:41:09.584286       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup-volume
I1031 02:41:09.584292       1 shared_informer.go:247] Caches are synced for longhorn-backup-volume 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Setting controller" controller=longhorn-setting node=master-1
I1031 02:41:09.584306       1 shared_informer.go:240] Waiting for caches to sync for longhorn settings
I1031 02:41:09.584316       1 shared_informer.go:247] Caches are synced for longhorn settings 
time="2022-10-31T02:41:09Z" level=info msg="Starting Longhorn backing image data source controller"
I1031 02:41:09.584324       1 shared_informer.go:240] Waiting for caches to sync for longhorn backing image data source
I1031 02:41:09.584330       1 shared_informer.go:247] Caches are synced for longhorn backing image data source 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Backup controller" controller=longhorn-backup node=master-1
I1031 02:41:09.584344       1 shared_informer.go:240] Waiting for caches to sync for longhorn-backup
I1031 02:41:09.584349       1 shared_informer.go:247] Caches are synced for longhorn-backup 
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Kubernetes node controller"
I1031 02:41:09.584425       1 shared_informer.go:240] Waiting for caches to sync for longhorn kubernetes node
I1031 02:41:09.584431       1 shared_informer.go:247] Caches are synced for longhorn kubernetes node 
time="2022-10-31T02:41:09Z" level=info msg=Start controller=longhorn-kubernetes-configmap-controller node=master-1
I1031 02:41:09.584440       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-configmap-controller
I1031 02:41:09.584445       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-configmap-controller 
time="2022-10-31T02:41:09Z" level=info msg="Starting Longhorn Snapshot Controller" controller=longhorn-snapshot node=master-1
I1031 02:41:09.584480       1 shared_informer.go:240] Waiting for caches to sync for longhorn-snapshot
I1031 02:41:09.584485       1 shared_informer.go:247] Caches are synced for longhorn-snapshot 
time="2022-10-31T02:41:09Z" level=warning msg="Failed to select node for sync backup target" controller=longhorn-setting error="no ready nodes available" node=master-1
time="2022-10-31T02:41:09Z" level=info msg="Start kubernetes controller"
I1031 02:41:09.584509       1 shared_informer.go:240] Waiting for caches to sync for kubernetes
I1031 02:41:09.584518       1 shared_informer.go:247] Caches are synced for kubernetes 
time="2022-10-31T02:41:09Z" level=warning msg="Error syncing Longhorn setting longhorn-system/backup-target" controller=longhorn-setting error="failed to sync setting for longhorn-system/backup-target: failed to sync backup target: no ready nodes available" node=master-1
time="2022-10-31T02:41:09Z" level=info msg="Start Longhorn Kubernetes secret controller" controller=longhorn-kubernetes-secret-controller node=master-1
I1031 02:41:09.584587       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-secret-controller
I1031 02:41:09.584595       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-secret-controller 
time="2022-10-31T02:41:09Z" level=info msg="Start longhorn-kubernetes-pod-controller" controller=longhorn-kubernetes-pod node=master-1
I1031 02:41:09.584646       1 shared_informer.go:240] Waiting for caches to sync for longhorn-kubernetes-pod-controller
I1031 02:41:09.584650       1 shared_informer.go:247] Caches are synced for longhorn-kubernetes-pod-controller 
time="2022-10-31T02:41:09Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=master-1
I1031 02:41:09.584245       1 shared_informer.go:240] Waiting for caches to sync for longhorn websocket
time="2022-10-31T02:41:09Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=master-1
I1031 02:41:09.584690       1 shared_informer.go:247] Caches are synced for longhorn websocket 
I1031 02:41:09.584048       1 shared_informer.go:240] Waiting for caches to sync for longhorn node
I1031 02:41:09.584697       1 shared_informer.go:247] Caches are synced for longhorn node 
time="2022-10-31T02:41:09Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=master-1
time="2022-10-31T02:41:09Z" level=warning msg="Cannot found the default backup target" controller=longhorn-kubernetes-secret-controller node=master-1
time="2022-10-31T02:41:09Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"master-3\", UID:\"0f815628-1e41-48f8-b319-e9c1c8a7cffc\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"4777370\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node master-3"
time="2022-10-31T02:41:09Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"master-2\", UID:\"6b14ef49-1af3-4b40-b57a-917758967179\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"4777365\", FieldPath:\"\"}): type: 'Warning' reason: 'Delete' Deleting node master-2"
time="2022-10-31T02:41:09Z" level=fatal msg="Error starting manager: create not allowed while custom resource definition is terminating"
[root@vm_10_161_34_15 longhorn]#

**Comment by nsmosi** [comment]
### OS: MacOS 12.6
### Rancher Desktop: Version: 1.7.0
### kubeletVersion: v1.25.6+k3s1

`# kubectl -n longhorn-system logs longhorn-manager-6qckx`

```
Defaulted container "longhorn-manager" out of: longhorn-manager, wait-longhorn-admission-webhook (init)
time="2023-02-14T03:46:02Z" level=error msg="Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host"
time="2023-02-14T03:46:02Z" level=fatal msg="Error starting manager: environment check failed: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 127"

```


`# kubectl -n longhorn-system describe pod longhorn-manager-6qckx`


```
Name:             longhorn-manager-6qckx
Namespace:        longhorn-system
Priority:         0
Service Account:  longhorn-service-account
Node:             lima-rancher-desktop/192.168.2.26
Start Time:       Mon, 13 Feb 2023 22:29:23 -0500
Labels:           app=longhorn-manager
                  app.kubernetes.io/instance=longhorn
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=longhorn
                  app.kubernetes.io/version=v1.4.0
                  controller-revision-hash=58b745dc54
                  helm.sh/chart=longhorn-1.4.0
                  pod-template-generation=1
Annotations:      <none>
Status:           Running
IP:               10.42.0.78
IPs:
  IP:           10.42.0.78
Controlled By:  DaemonSet/longhorn-manager
Init Containers:
  wait-longhorn-admission-webhook:
    Container ID:  containerd://c7aef76971ac2a76bdee9efd16ae9907fc98679366e4ad41bc22b2538958d765
    Image:         longhornio/longhorn-manager:v1.4.0
    Image ID:      docker.io/longhornio/longhorn-manager@sha256:15d87b1029b77c61130852e42e85abaa88f029e0ad6519af892e22fd6e7c2ad8
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" -k https://longhorn-admission-webhook:9443/v1/healthz) != "200" ]; do echo waiting; sleep 2; done
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 13 Feb 2023 22:29:44 -0500
      Finished:     Mon, 13 Feb 2023 22:29:55 -0500
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xbd6g (ro)
Containers:
  longhorn-manager:
    Container ID:  containerd://a35483e419c6669ea1ae891fac8b5afa7e6b2a764ee62cfeb5b2d1aad15dee19
    Image:         longhornio/longhorn-manager:v1.4.0
    Image ID:      docker.io/longhornio/longhorn-manager@sha256:15d87b1029b77c61130852e42e85abaa88f029e0ad6519af892e22fd6e7c2ad8
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.4.0
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1.4.0
      --share-manager-image
      longhornio/longhorn-share-manager:v1.4.0
      --backing-image-manager-image
      longhornio/backing-image-manager:v1.4.0
      --support-bundle-manager-image
      longhornio/support-bundle-kit:v0.0.17
      --manager-image
      longhornio/longhorn-manager:v1.4.0
      --service-account
      longhorn-service-account
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 13 Feb 2023 22:46:02 -0500
      Finished:     Mon, 13 Feb 2023 22:46:02 -0500
    Ready:          False
    Restart Count:  8
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:  longhorn-system (v1:metadata.namespace)
      POD_IP:          (v1:status.podIP)
      NODE_NAME:       (v1:spec.nodeName)
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /tls-files/ from longhorn-grpc-tls (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xbd6g (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:  
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:  
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:  
  longhorn-grpc-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-grpc-tls
    Optional:    true
  kube-api-access-xbd6g:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  21m                  default-scheduler  Successfully assigned longhorn-system/longhorn-manager-6qckx to lima-rancher-desktop
  Normal   Pulling    21m                  kubelet            Pulling image "longhornio/longhorn-manager:v1.4.0"
  Normal   Pulled     21m                  kubelet            Successfully pulled image "longhornio/longhorn-manager:v1.4.0" in 18.757994s (18.758034s including waiting)
  Normal   Created    21m                  kubelet            Created container wait-longhorn-admission-webhook
  Normal   Started    21m                  kubelet            Started container wait-longhorn-admission-webhook
  Normal   Pulled     20m (x4 over 21m)    kubelet            Container image "longhornio/longhorn-manager:v1.4.0" already present on machine
  Normal   Created    20m (x4 over 21m)    kubelet            Created container longhorn-manager
  Normal   Started    20m (x4 over 21m)    kubelet            Started container longhorn-manager
  Warning  BackOff    108s (x95 over 21m)  kubelet            Back-off restarting failed container

```

**Comment by fabltd** [comment]
Hi All 

I have this error:

```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3+k3s2
```

The pods fail - longhorn-manager-fhhkb                      0/1     CrashLoopBackOff    

I have tried running:

`curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/master/scripts/environment_check.sh | bash`

Still fails. Where to debug next ?

**Comment by cyford** [comment]
I am having the same issue..   on 1 out of 16  differnt servers
<img width="821" alt="image" src="https://github.com/longhorn/longhorn/assets/25903490/e7d6672f-ce43-4ba1-a9ae-3c7819f44474">

**Comment by tonyliu666** [comment]
> I am having the same issue.. on 1 out of 16 differnt servers <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/25903490/290011495-e7d6672f-ce43-4ba1-a9ae-3c7819f44474.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjEyMzIsIm5iZiI6MTcxMTQ2MDkzMiwicGF0aCI6Ii8yNTkwMzQ5MC8yOTAwMTE0OTUtZTdkNjY3MmYtY2U0My00YmExLWE5YWUtM2M3ODE5ZjQ0NDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzNDg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NGU4ZjBlZWVjYTcyYWM0MDYwYmY2MTFjMDM3N2Q4NWE2ZjliODk2ZTc4Yzg4YzNiMTU1Mzc2ZDZhYTBmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmC5s_4kB0StR0LD5TFeBrSezkJcnv_pbaFjwsGsD2Y">

I also have the same outputs. Did you fix this issue?

**Comment by q2booster** [comment]
Me too, using helm 
```
helm repo add longhorn https://charts.longhorn.io

helm repo update

helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --version 1.7.2
```
