### ISSUE TITLE
[FEATURE] Reclaim/Shrink space of volume

### ISSUE THREAD

**Issue by IAkumaI** [longhorn/longhorn#836]
Hello, I khow volumes can grow only, but what if I need to reclaim space of deleted files?
Is there other choice but remove/create volume?

**Comment by yasker** [comment]
@IAkumaI 

I don't think there is another way to reclaim the space of deleted files. Regarding the total size of the volume, you might reclaim some by removing old snapshots.

**Comment by yasker** [comment]
Maybe we can try to implement `trim` on iscsi target.

**Comment by SeMeKh** [comment]
@yasker I'm willing to spend some time on this. Any pointers on where and how the code should be changed?

**Comment by yasker** [comment]
@SeMeKh Thanks!

After thinking more about it, I realized it's probably not a good idea to implement this.

My idea was by implementing `TRIM` command in iSCSI target (https://github.com/rancher/tgt/blob/longhorn_oct2019/usr/bs_longhorn.c#L80 ), we would know which area is no longer used by the filesystem. We will need a new command (https://github.com/longhorn/longhorn-engine/blob/master/pkg/engine/dataconn/types.go#L6) in data connection protocol to tell us about the TRIM. 

Longhorn's snapshot is immutable. That means we can only save the space in the `volume head` by punching holes in the `volume head` (similar to what we do in https://github.com/longhorn/sparse-tools/blob/50ffab4d432962b913d1497fd77f4878caf94077/sparse/rest/handlers.go#L119 ). So I am not sure if it's worth the effort.

The most helpful case would be the user write and delete a lot of data in the `volume head`, without making any snapshots. Once a snapshot was made, `TRIM` command will not be more helpful. It also depends on how OS uses `TRIM`. So it's a bit unclear how helpful this will be.

@SeMeKh If you want to take a look at other Longhorn issues instead, feel free to let me know.

**Comment by SeMeKh** [comment]
@yasker Thanks for the explanation.

I experimented with running `fstrim` directly on the underlying file, and it did free up space. I'm afraid that could cause inconsistencies though. Do you think there is a feasible way to avoid losing the consistency, given that I am willing to avoid using snapshots if that's the cost?

**Comment by yasker** [comment]
@SeMeKh Losing the snapshot is not really an option. If you take a look at `Replica Operations` section in https://rancher.com/blog/2017/announcing-longhorn-microservices-block-storage/ , snapshots are the foundations of Longhorn. We rely on `holes` in the snapshots to know where is the data stored. TRIM can potentially change that. I think TRIM may change previous data into holes, so a read before TRIM supposes to read at snapshot C, but since snapshot C was trimmed and some new holes are created, Longhorn would see the hole (instead of empty data), continue reading on snapshot B and A, which result in data reading error.

It's just an assumption at this point. We can do more experiments and understand more about the potential impacts.

**Comment by oscni** [comment]
This has been a problem day one since hypervisors came along. You create for an example a 100GB disc and initially the VM installation takes up 30GB. But since the filesystems writes new data pretty much randomly over the the disc after a while the hypervisor will report 100GB usage even though you might only use 60GB inside the VM. Same thing seems to apply here with the containers and longhorn. For OS and hypervisors it has been solved with TRIM,UNMAP,discard,deletenotification etc. Anything is possible and nothing is free so it would be good if this can be prioritized otherwise it feels like a step back in the storage evolution.

**Comment by jamesharr** [comment]
I think the tricky part is the way snapshots are layered on a replica. Longhorn relies on [hole detection](https://lwn.net/Articles/260795/) to realize that data is on a snapshot layer below it. Say that snapshot has data when a hole is punched in the active image, then what should be all 0's turns into old-data pulled from the snapshot. From a security perspective (especially with iSCSI) if you zero a block, that data better not come back.

A couple ideas that could implement TRIM without adding metadata.
1) Check all the snapshot layers for holes before punching a hole. Only punch a hole if all of the underlying layers have holes as well
2) periodically scan for areas where a hole could be punched.

Those ideas might be more difficult than it's worth and there is a price to them. If you have a chain of 20 snapshots, you have to check for a hole in 20 files. Not exactly ideal.

I'm still interested in this feature, but after hearing how tricky this is, I'm willing to wait. It's not a problem for us. SSD TRIM is helps extend the life and performance of the drives, so passing it down to the underlying hardware is still something to keep an eye on, in my opinion.

**Comment by immanuelfodor** [comment]
I have a related but may be a bit different question. How to reclaim space by a removed _first_ snapshot? My 5G volume became fully utilized by the stored ~300MB data and some experimentation with `dd` to see how a volume grows, then I deleted a replica (as part of learning Longhorn to also see what happens), it created a snapshot automatically to recover the lost replica, then I removed that snapshot but it never really disappeared.

```bash
# in the attached pod
$ df -h
Filesystem                                                            Size  Used Avail Use% Mounted on
/dev/longhorn/pvc-c0747652-32ce-4f68-b769-f7ff104ef0fd                4.9G  312M  4.6G   7% /config

# on a node
$ ls -la /var/lib/longhorn/replicas/pvc-c0747652-32ce-4f68-b769-f7ff104ef0fd-435f8290/
total 5119048
drwx------. 2 root root        233 Mar 22 22:11 .
drwxr-xr-x. 4 root root        120 Mar 22 20:44 ..
-rw-------. 1 root root       4096 Mar 23 09:41 revision.counter
-rw-r--r--. 1 root root 5368709120 Mar 23 09:41 volume-head-004.img
-rw-r--r--. 1 root root        178 Mar 22 22:06 volume-head-004.img.meta
-rw-r--r--. 1 root root        194 Mar 22 22:06 volume.meta
-rw-r--r--. 1 root root 5368709120 Mar 22 22:11 volume-snap-275d6f37-451e-45a2-91e1-d26ec2dfd8b5.img
-rw-r--r--. 1 root root        158 Mar 22 22:11 volume-snap-275d6f37-451e-45a2-91e1-d26ec2dfd8b5.img.meta
```

Still on the node by `ncdu`:

![image](https://user-images.githubusercontent.com/21174107/112203240-9b6f6180-8c12-11eb-8025-4dff0d0b790a.png)

On the UI:

![image](https://user-images.githubusercontent.com/21174107/112201905-0e77d880-8c11-11eb-8639-a61b3592d3ca.png)

![image](https://user-images.githubusercontent.com/21174107/112201949-1c2d5e00-8c11-11eb-9a52-25f1e9222395.png)

I would expect deleting a snapshot removes that snapshot from the disk, and only the head remains if it was the first snapshot. If it's not the case for the 1st snapshot but only for the 2nd and later, I can accept that as something would still be 5G as far as I understand, if not the first snapshot, then the volume head as Longhorn operates on the block level.

And this is where I can join the original conversation, it would be great to be able to reclaim that 4.7G space lost by experimentation (than later by some IO operations). Maybe I could run `fstrim` from within the attached pod? It's effect could sync to all replicas after that, couldn't it?

**Comment by immanuelfodor** [comment]
After reading this masterpiece (https://github.com/longhorn/longhorn/issues/1555#issuecomment-671097588), I feel I've run into the same issue as others :grinning: 

However, these two questions might still be valid:
- Why is the removed snapshot still present on the disk? Maybe it was the first and this is the way Longhorn works with the volume head never replacing back the first snapshot?
- Could we `fstrim` from within the attached pod to propagate the change to the replicas as well? So not from the node which can be of course inconsistent but from the application using the volume? Or not supporting TRIM is also true from this viewpoint?

**Comment by immanuelfodor** [comment]
I could reclaim the 4.7G space on all replicas with a simple script to recreate the volume with a backup to a `hostPath` PV. As Jellyfin temporarily stores movie transcodes on the config volume which can take up hundreds of megabytes, I can semi-automate the PV recreation this way when the Actual Size will take up too much space over the ~300MB of base files.

**migrate-longhorn.yml**

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migrate
  namespace: media
  labels:
    app: migrate
spec:
  selector:
    matchLabels:
      app: migrate
  template:
    metadata:
      labels:
        app: migrate
    spec:
      containers:
        - image: alpine
          name: alpine
          command:
          - /bin/sh
          args:
          - -c
          - sleep 50000
          volumeMounts:
            - name: config
              mountPath: "/config"
            - name: config-bak
              mountPath: "/config-bak"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: config-bak
          hostPath:
            path: /srv/hostpath/jellyfin
            type: DirectoryOrCreate
      nodeName: node2
```

**recreate-longhorn.sh**

```bash
#!/bin/bash

set -xe

kubectl -n media scale deployment jellyfin --replicas=0
kubectl -n media rollout status deployment jellyfin

kubectl -n media apply -f migrate-longhorn.yml
kubectl -n media rollout status deployment migrate

kubectl -n media exec -it deployment/migrate -- sh -c 'ls -la /config /config-bak'
kubectl -n media exec -it deployment/migrate -- sh -c 'rm -rf /config-bak/*'
kubectl -n media exec -it deployment/migrate -- sh -c 'cp -a /config/* /config-bak'
kubectl -n media exec -it deployment/migrate -- sh -c 'rm -rf /config-bak/lost+found'
kubectl -n media exec -it deployment/migrate -- sh -c 'ls -la /config /config-bak'

kubectl -n media delete -f migrate-longhorn.yml

yq r jellyfin.yml -d 0 | kubectl delete -f -
yq r jellyfin.yml -d 0 | kubectl apply -f -

kubectl -n media apply -f migrate-longhorn.yml
kubectl -n media rollout status deployment migrate

kubectl -n media exec -it deployment/migrate -- sh -c 'ls -la /config /config-bak'
kubectl -n media exec -it deployment/migrate -- sh -c 'cp -a /config-bak/* /config'
kubectl -n media exec -it deployment/migrate -- sh -c 'ls -la /config /config-bak'

kubectl -n media delete -f migrate-longhorn.yml

kubectl -n media scale deployment jellyfin --replicas=1
kubectl -n media rollout status deployment jellyfin
```

The `yq r jellyfin.yml -d 0` output is the config volume claim:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "jellyfin-config"
  namespace: "media"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
  storageClassName: "longhorn"
```

It could be done more efficiently with `emptyDir` volume and without the `exec`s using container command/args but this was easier to debug and I felt safer not to have accidental data loss.

**Comment by matthewd1826** [comment]
New to Longhorn, but is there a way to allocate a new volume, and copy the data over to it, in order to reclaim the space, then mount the new volume in place of the old volume, then delete the old volume? By copying the data over, it would only use as much space that is actually currently used.

**Comment by kirinnee** [comment]
Hi, we have this problem too. We don't really need snapshots since we are using Prometheus, and the longhorn volume is monotonically increasing despite us having set a retention size. Is there a work-around or anyway forward with using longhorn volume for write-delete heavy applications?

**Comment by joshimoo** [comment]
@kirinnee Currently we don't support trim, so the only advice I can give don't over provision your PVC, allocate the maximum expected file system size as your PVC volume size. Then if you don't use snapshot, your volume will not grow bigger then the maximum capacity since each snapshot is bound by that capacity. (live head is also a snapshot)

**Comment by kirinnee** [comment]
@joshimoo  Hi, it seems to still grow bigger than the maximum capacity. I'm not sure if I'm doing this right - correct me if I'm wrong. 
![image](https://user-images.githubusercontent.com/15990242/121039528-bdc15600-c7e3-11eb-8936-d64202178bc7.png)

**Comment by kirinnee** [comment]
Just in case, there's no snapshot with regards to this volume:
![image](https://user-images.githubusercontent.com/15990242/121040700-b2baf580-c7e4-11eb-85a5-52c7284e52ac.png)

**Comment by joshimoo** [comment]
@kirinnee can you flip the switch to `show System Hidden` I am guessing you had some replica rebuild events, that left system snapshots behind?

**Comment by kirinnee** [comment]
![image](https://user-images.githubusercontent.com/15990242/121041998-d894ca00-c7e5-11eb-9476-50f0861b2b7c.png)


Hi, that seems like the case. Can I trouble you to give me some readings on how replica rebuild events are triggered?

**Comment by rapsspider** [comment]
I have the same problem as @kirinnee . My PVC size is 20Go, but it's seem possible to grow up as 37Go ...

![image](https://user-images.githubusercontent.com/8452428/121651295-c1323700-ca9a-11eb-9b85-7feee41ce2c3.png)

At this miment, I have a volume that grow without activity (PVC 20Go with now 26,1Go size showed by longhorn). And in the pod, with a df -h, I only have 2,8Go, so, it's weird :).

**Comment by eminalemdar** [comment]
I have the same problem with some Volumes. Volumes don't have any snapshots and there is nothing when I click the `Show Hidden` button as well. This is going to be a huge problem for us in the near future because we can't reclaim disk space when we delete data.

**Comment by MittWillson** [comment]
same problems here, any progress?

**Comment by vitobotta** [comment]
Same thing. For example I have a volume for a Clickhouse database with nominal size of 30Gi. The actual data takes only 3-400MBs but the Longhorn volume's actual size is already at 6.5GB after a few days and I don't know why. There have been no rebuilds, there are no snapshots either created by me/recurring job, nor system snapshots.

**Comment by eminalemdar** [comment]
Having a manual or automatic or some kind of scheduled space reclamation option would be a perfect solution for this issue. Everyone always deletes some data from the filesystem all the time. Backups are created using system snapshots as well and that is also increasing the actual size of the volume.

**Comment by bork91** [comment]
@yasker is there any news on when this problem will be fixed?

**Comment by joshimoo** [comment]
Not at the moment, best advice is to not over provision your volume during creation.
If you are only expecting 10GB usage then no need to provision 100GB, since you can grow the pvc -> volume in the future when needed.

**Comment by voarsh2** [comment]
![image](https://user-images.githubusercontent.com/60437695/159535063-82af8ad0-44f0-43a6-b56d-309b66c02834.png)
![image](https://user-images.githubusercontent.com/60437695/159535174-c6520b94-cf6b-4a23-9bb6-af7f5c8a9f64.png)
![image](https://user-images.githubusercontent.com/60437695/159535375-b0312e45-21fa-48af-a0ac-907a8990f151.png)

Would be nice to reclaim the space. Makes it quite hard to see how much space is left in the volume.

**Comment by keithalucas** [comment]
I'm assuming that trimming the filesystem will effectively mark blocks as "don't care" blocks, i.e. the file system isn't using them and if it uses them in the future it will overwrite them.  ext4 and xfs both have discard mount options which look like they might automatically trim the block device as it is being used.

TGT can receive an [UNMAP](https://github.com/rancher/tgt/blob/e042fdd3616ca90619637b5826695a3de9b5dd8e/usr/scsi.h#L64) SCSI command, but the longhorn block device in tgt doesn't handle it.  I believe the UNMAP SCSI command corresponds to the trimming.   We could test added support for the UNMAP command and punch a hole in the volume's sparse file for the offset and length specified in the command.  If there are no snapshots, this will zero the command.   If there are snapshots, reading data at the unmapped offset could return data from one of the snapshots.  If the potential for returning inconsistent data may not be important for filesystem if it unmapped the data.   We should confirm that the filesystem is consistent after unmapping.

To try this out, we will need to:
1. Make tgt handle the UNMAP SCSI command and verify that the discard mount option or manually running `fstrim` cause the UNMAP SCSI command to be sent to the longhorn block device.
2. Add unmap command with offset and length to liblonghorn.
3. Add unmap to pkg/dataconn in longhorn-engine and forward all unmap commands from the longhorn-engine controller to all replicas.
4. Add support to the longhorn-engine replica to punch holes when it receives an unmap command.
5. Verify that an ext4 or xfs filesystem mounted with the discard option works with work flows that involve creating and deleting many files and the disk usages for that volume is smaller than without the change.

**Comment by korenlev** [comment]
will xfs file system make any different ?

**Comment by korenlev** [comment]
https://docs.portworx.com/reference/cli/volume-trim/

**Comment by yasker** [comment]
@keithalucas we need to be careful about the data we returned if a block is claimed as `unmapped`.

I agree that if a block is unmapped/trimmed, the user shouldn't care about it. However, there are two concerns if there are snapshots exist in the system:
1. As a block storage provider, what's the defined behavior for reading if a block is `trimmed`? Would the user expect 0 or anything from reading? We need to find more info about it or define it ourselves.
2. Would it be a security concern if we just read through the previous snapshots? since that data can still be directly read from the disk if you bypass the filesystem.

**Comment by jamesharr** [comment]
Agreed on the security concern of getting back data that was previously trimmed.

I have a couple other points I figure I'd add in:

There's also this implicit agreement that if a block is TRIMed, it will be zeros if/when read in the future. This may or may not be written into a spec anywhere, but the behavior is ubiquitous if the device supports trim.

I recognize your proposed work around though. It is a clever solution.

I'd like to see this solved eventually, but I expect it'll just take managing a block map or mask of some sort.

**Comment by iosifnicolae2** [comment]
Here is how we shrink'ed a disk manually: https://github.com/longhorn/longhorn/discussions/4178.

**Comment by korenlev** [comment]
Scale all deployments using the volumes to 0

In production ??

Let's continue trying to get a production solution

**Comment by yl-yue** [comment]
Hi, maybe we can escalate the priority of this issue, it will no longer be an enhancement feature, but a **level 1 bug**, as it has caused serious production incidents in our production environment.

The explanation is as follows:

When the actual size of the volume exceeds the nominal size, longhorn will consider the disk space of this node to be unschedulable, which will cause all `pvc` mounted on this node to hang (if the pod is restarted), resulting in the node hang up, causing the service deployed in the cluster to hang up (ie: serious production accident)

What's even scarier is that the data recovery of the cluster is catastrophic. If the pvc volume is not backed up, the data will be completely lost, because the actual size of the volume is constantly expanding, and the node to which the volume is mounted has been marked as unschedulable. At this time, if the program continues to write a large amount of data to this volume, the volume will be completely damaged and cannot be repaired (the node hard disk actually still has a lot of space `df -h`)

If the volume of data is too large, the recovery time of the volume will also be very, very long, starting at least half a day, and your production environment is always in a waiting state (suspended) during this process.

We have tested in the production environment, if the amount of data is only 300GB, it will only take about an hour for us to perform remote recovery through data replication, and it will take at least several hours or even longer to achieve remote recovery through `longhron`.

Summary: Longhorn is currently not suitable for scenarios with large amounts of data (such as logs, monitoring), nor for scenarios with large amounts of data deletion.

**Comment by shuo-wu** [comment]
Thank you for @keithalucas's investigation and reporting. In brief, users should take their own risk of the data from the trimmed part being read if someone has access to the raw block device of the filesystem, right?

**Comment by shuo-wu** [comment]
> When the actual size of the volume exceeds the nominal size, longhorn will consider the disk space of this node to be unschedulable, which will cause all pvc mounted on this node to hang (if the pod is restarted), resulting in the node hang up, causing the service deployed in the cluster to hang up (ie: serious production accident)

I am suspecting the exceeded data on the cluster nodes triggers the **Kubernetes node disk pressure** issue. Then the Kubernetes node becomes unscheduable. 
Right now there is no way for Longhorn to prevent the volume from continuing consuming space even if the rest free disk space is limited. By default, Longhorn enables volume over-provisioning. It's possible to trigger the disk pressure issue/Kubernetes node unscheduable issue as well if you create a large volume (of which spec size is greater than the disk free space) and try to fill up it (no snapshot in this case hence the actual size won't exceed the spec value). To avoid the issue(it's hard to eliminate it now), it's better to set an appropriate over-provisioning value based on the use case.

**Comment by R-Studio** [comment]
This is really **level 1 bug** for us, as @yl-yue says! 😰
Is it somehow possible to fix this bug before release v1.4.0 (v1.4.0 is planned for january 2023😯)?

_Because of this bug we have to use NFS instead of Longhorn for multiple production workloads._ 😢

**Comment by shuo-wu** [comment]
Typically this kind of important feature won't be put into patch releases (v1.3.x) since it may have unpredictable impacts on the stability/robustness.

**Comment by FaraSys** [comment]
I want to advise my way how to reduce Actual size without data loss.
It is necessary to reduce the number of replicas to 1, and then increase.
 For example You have pvc-123 on node 1. The original size is 20GB, the actual size is 29GB(In long UI), Let's increase the replica to 2. Now pvc-123 node1 and pvc-456 node2. After the rebuild, we remove pvc-123 and the actual size will decrease.

**Comment by yl-yue** [comment]
**issue**

> #3888 #2510 #3423 #3120

**discussions**

> https://github.com/longhorn/longhorn/discussions/4178

**Comment by migs35323** [comment]
Please make it happen, I have some volumes that grow up to 100+ GB because that space was used at some point. one of the volumes now has about 8 GB in files and it's just ridiculous to deal with replicas and backups of 100GB...
Limit the max size is not really a solution, we allocate large volumes so we don't need to manually adjust them once we require more storage...

**Comment by nitin992vij** [comment]
If the actual size of the volume doesn't get shrunk, then how can we monitor the volume. 
In Our case we created a Grafana Dashboard for monitoring Longhorn Volumes and was planning to create an Alert once the usage is above 70% , but when usage level goes below the threshold the alerts still remain active as Longhorn Volume doesn't get shrunk.
![image](https://user-images.githubusercontent.com/45073684/195538460-86a7320e-b62f-4071-85dc-a617c2dc03d5.png)

**Comment by innobead** [comment]
@shuo-wu It seems straightforward but still needs an LEP for the feature review/understanding of the overall features and user behavior, especially about snapshot management. Added `require/LEP`.

**Comment by kladiv** [comment]
+1 really great feature

**Comment by roger-ryao** [comment]
**Verified on master-head 20221213**

- longhorn master-head ([aa3998e](https://github.com/longhorn/longhorn/commit/aa3998ee3a145e4a3f4c282ddf66bc536e6b114c)) 
- longhorn-manager master-head ([4a758e7](https://github.com/longhorn/longhorn-manager/commit/4a758e7efcba0cd69f9beb1bc7c903f5541a3c3b))
- longhorn-instance-manager master-head ([7026fbc](https://github.com/longhorn/longhorn-instance-manager/commit/7026fbc454ef8273b58efe0e56451a739208d59e)) 

**The test steps**

[test-filesystem-trim](https://github.com/longhorn/longhorn-tests/blob/8c0a9216d0e82775a16c55c12c2198b6a9a9b195/docs/content/manual/release-specific/v1.4.0/test-filesystem-trim.md)

**Result Passed**

Case 1: Test filesystem trim during writing
  - The script execution succeed, we didn't get the error message on the console.
  - ![Screenshot_20221213_104355](https://user-images.githubusercontent.com/104337648/207213462-ccf1a77a-591a-49ac-92f4-a0ed7d39b075.png)


Case 2: Test flag `unmapMarkSnapChainRemoved` unchanged after volume engine upgrade
  - After upgraded volume with another engine image, 
     we saw the `"Get backend <replica address> UnmapMarkSnapChainRemoved true"`
     we could not see the `"Set backend <replica address> UnmapMarkSnapChainRemoved true"`
  - ![Screenshot_20221213_100337](https://user-images.githubusercontent.com/104337648/207209584-98fc051a-c35d-48f4-a99f-b3f65e6ef8de.png)


cc @shuo-wu

**Comment by korenlev** [comment]
Amazing fix

בתאריך יום ג׳, 13 בדצמ׳ 2022, 9:24, מאת oscni ***@***.***>:

**Comment by tommy04062019** [comment]
> **Verified on master-head 20221213**
> 
> * longhorn master-head ([aa3998e](https://github.com/longhorn/longhorn/commit/aa3998ee3a145e4a3f4c282ddf66bc536e6b114c))
> * longhorn-manager master-head ([4a758e7](https://github.com/longhorn/longhorn-manager/commit/4a758e7efcba0cd69f9beb1bc7c903f5541a3c3b))
> * longhorn-instance-manager master-head ([7026fbc](https://github.com/longhorn/longhorn-instance-manager/commit/7026fbc454ef8273b58efe0e56451a739208d59e))
> 
> **The test steps**
> 
> * [test-filesystem-trim](https://github.com/longhorn/longhorn-tests/blob/8c0a9216d0e82775a16c55c12c2198b6a9a9b195/docs/content/manual/release-specific/v1.4.0/test-filesystem-trim.md)
> 
> **Result Passed**
> 
> Case 1: Test filesystem trim during writing
> 
> * The script execution succeed, we didn't get the error message on the console.
> * ![Screenshot_20221213_104355](https://user-images.githubusercontent.com/104337648/207213462-ccf1a77a-591a-49ac-92f4-a0ed7d39b075.png)
> 
> Case 2: Test flag `unmapMarkSnapChainRemoved` unchanged after volume engine upgrade
> 
> * After upgraded volume with another engine image,
>   we saw the `"Get backend <replica address> UnmapMarkSnapChainRemoved true"`
>   we could not see the `"Set backend <replica address> UnmapMarkSnapChainRemoved true"`
> * ![Screenshot_20221213_100337](https://user-images.githubusercontent.com/104337648/207209584-98fc051a-c35d-48f4-a99f-b3f65e6ef8de.png)
> 
> cc @shuo-wu
@roger-ryao : great to hear that but  the longhorn volume still shows more space than the actual size after deleting the content, right? Am I misunderstanding something here? Some info bellow
- Longhorn: v1.4.0(install from master branch)
- Create Longhorn Volume: 10GB
- Allow snapshots removal during trim:enabled(true)
- Create some file tests then delete them.
- Show file system info:
<img width="936" alt="Screen Shot 2022-12-21 at 11 59 08" src="https://user-images.githubusercontent.com/8014325/208825173-e4ecf240-fc46-4579-921b-b1c9a79aea21.png">
- Show volume from Longhorn UI:

<img width="453" alt="Screen Shot 2022-12-21 at 12 00 11" src="https://user-images.githubusercontent.com/8014325/208825292-a8ea544a-01c6-4e73-8ad2-af6e4ebb515b.png">

**Comment by yangchiu** [comment]
@tommy04062019 did you trigger filesystem trim?

**Comment by tommy04062019** [comment]
> 



> @tommy04062019 did you trigger filesystem trim?

Do you mean I have to go to Longhorn UI, choose the Volume and click on `Trim Filesystem`? I did, but it has failures
<img width="1435" alt="Screen Shot 2022-12-22 at 09 48 32" src="https://user-images.githubusercontent.com/8014325/209044632-c63f6fe2-51f7-44d1-8001-c8a77f24dd09.png">
<img width="1421" alt="Screen Shot 2022-12-22 at 09 48 53" src="https://user-images.githubusercontent.com/8014325/209044688-ac586946-0ec3-4905-9b6a-edd2ce12295d.png">

**Comment by yangchiu** [comment]
@shuo-wu @longhorn/dev 
Do we have any prerequisite before trigger `Trim Filesystem`?

Just create workloads to use Longhorn volume, like:
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/deployment.yaml`
or
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml`

Then triggered `Trim Filesystem` from Longhorn UI for each volume, I can observe different error messages shown up like:

`unable to trim filesystem for volume test-1: zero or multiple mount points for volume test-2: [/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/e063cdf36f817a24e97839b0799c023644dd1c31c668bda6481869027035a655/globalmount /var/lib/kubelet/pods/c63d1f31-0a5c-40c1-b4d6-2a70f7f14200/volumes/kubernetes.io~csi/test-1/mount]`

or:

`unable to trim filesystem for volume pvc-3155fa88-7f2d-423b-9e95-7c840c5d916f: cannot find volume pvc-3155fa88-7f2d-423b-9e95-7c840c5d916f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`

**Comment by innobead** [comment]
cc @derekbit @shuo-wu

**Comment by derekbit** [comment]
> unable to trim filesystem for volume test-1: zero or multiple mount points for volume test-2

There are two mountpoints 
```
/dev/longhorn/<pvc name> on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/<pvc name>/globalmount type ext4 (rw,relatime)
/dev/longhorn/<pvc name> on /var/lib/kubelet/pods/xxxx/volumes/kubernetes.io~csi/<pvc name>/mount type ext4 (rw,relatime)
```
The first on is created by `NodeStageVolume` and the second one is a bind mount created by `NodePublishVolume`.

The request is rejected by https://github.com/longhorn/longhorn-manager/blob/master/util/util.go#L922.
From the `fstrim` [spec](https://man7.org/linux/man-pages/man8/fstrim.8.html), trimming a volume with multiple mountpoints is not forbidden. Not sure if there is any concern.

**Comment by innobead** [comment]
The second mount is just a bind mount of the global mount, so we should treat it the same. We should do fstrim against the global mount.

@roger-ryao this function did not work, so we need to revisit how we test it. cc @longhorn/qa 

@tommy04062019 thanks for the feedback :+1:

**Comment by innobead** [comment]
@yangchiu Please re-validate this. Thanks.

**Comment by yangchiu** [comment]
@derekbit Are we able to trim filesystem for a `RWX` volume?

I create a workload using Longhorn RWX volume:
`kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`

And try to trim filesystem from Longhorn UI, it gives the following error message:
`unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`

**Comment by tommy04062019** [comment]
> @derekbit Are we able to trim filesystem for a `RWX` volume?
> 
> I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> 
> And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`

Same error with RWO:
`unable to trim filesystem for volume pvc-858062c5-baef-472b-99fa-feb98a785574: cannot find volume pvc-858062c5-baef-472b-99fa-feb98a785574 mount info on host: failed to execute: nsenter [--mount=/host/proc/985/ns/mnt --net=/host/proc/985/ns/net fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574/globalmount: FITRIM ioctl failed: Remote I/O error : exit status 1`

**Comment by derekbit** [comment]
> > @derekbit Are we able to trim filesystem for a `RWX` volume?
> > I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> > And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`
> 
> Same error with RWO: `unable to trim filesystem for volume pvc-858062c5-baef-472b-99fa-feb98a785574: cannot find volume pvc-858062c5-baef-472b-99fa-feb98a785574 mount info on host: failed to execute: nsenter [--mount=/host/proc/985/ns/mnt --net=/host/proc/985/ns/net fstrim /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574/globalmount], output , stderr fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574/globalmount: FITRIM ioctl failed: Remote I/O error : exit status 1`

@yangchiu 
I never tried RWX. Will check it again. But the error message means the mount point is not existing.

@tommy04062019 
RWX as well? The error message shows up error. Can you provide the steps to reproduce?

**Comment by tommy04062019** [comment]
> @tommy04062019
> The error message shows io error. Can you provide the steps to reproduce?

@derekbit Steps I made to test as bellow:
- Install longhorn with `v1.4.x-head` version
- Run deployment with  volume of 10GB : `https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml`
- Create some test file and then deleting them.
<img width="1128" alt="Screen Shot 2022-12-23 at 09 27 32" src="https://user-images.githubusercontent.com/8014325/209258783-c28581bd-c3f2-4f01-9602-683993d1f03f.png">

- Go to Longhorn UI
<img width="448" alt="Screen Shot 2022-12-23 at 09 28 22" src="https://user-images.githubusercontent.com/8014325/209258870-f869494e-8e69-4630-8185-4ddd2cc67f4e.png">

- Execute `Trim Filesystem` and it shown an error as I comment above
- `fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574/globalmount: FITRIM ioctl failed: Remote I/O error : exit status 1` --> I think `fstrim` command should be: `fstrim fstrim: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-858062c5-baef-472b-99fa-feb98a785574` without `globalmount`

**Comment by yangchiu** [comment]
@tommy04062019 Sorry but since I'm failed to reproduce the error you encountered, could you help to provide more information about your test steps? Like how/what you created/deleted the test files? did you take snapshots or do any other operations? And if other environment information like OS, k8s distro version can be provided would be very appreciated. Thank you!

**Comment by tommy04062019** [comment]
> @tommy04062019 Sorry but since I'm failed to reproduce the error you encountered, could you help to provide more information about your test steps? Like how/what you created/deleted the test files? did you take snapshots or do any other operations? And if other environment information like OS, k8s distro version can be provided would be very appreciated. Thank you!

This is my environment:
- Rancher : v2.5.15 (or v2.7.0)
- Kubernetes Version: v1.21.12
- OS worker: Ubuntu 20.04

Here is how I tested created/deleted files.
- After pod is running I access to shell
- cd to the mountpoint of Longhorn volume in the pod.

```
dd if=/dev/zero of=2gbfile-1 bs=2G count=1
dd if=/dev/zero of=2gbfile-2 bs=2G count=1
sync
rm 2gbfile-1
```

- On Longhorn UI, I did not take any snapshots, I just go to the volume and execute `Trim Filesystem` function.

Tell me if you need more info. Thank

**Comment by yangchiu** [comment]
> > @tommy04062019 Sorry but since I'm failed to reproduce the error you encountered, could you help to provide more information about your test steps? Like how/what you created/deleted the test files? did you take snapshots or do any other operations? And if other environment information like OS, k8s distro version can be provided would be very appreciated. Thank you!
> 
> This is my environment:
> 
>     * Rancher : v2.5.15 (or v2.7.0)
> 
>     * Kubernetes Version: v1.21.12
> 
>     * OS worker: Ubuntu 20.04
> 
> 
> Here is how I tested created/deleted files.
> 
>     * After pod is running I access to shell
> 
>     * cd to the mountpoint of Longhorn volume in the pod.
> 
> 
> ```
> dd if=/dev/zero of=2gbfile-1 bs=2G count=1
> dd if=/dev/zero of=2gbfile-2 bs=2G count=1
> sync
> rm 2gbfile-1
> ```
> 
>     * On Longhorn UI, I did not take any snapshots, I just go to the volume and execute `Trim Filesystem` function.
> 
> 
> Tell me if you need more info. Thank

With `ubuntu 20.04` + `k3s v1.21.12+k3s1` + `longhorn v1.4.x-head` and following the above operations, I'm still unable to reproduce this. Currently I don't have any clue. @derekbit Do you have any insight into what will possibly cause this error?

**Comment by tommy04062019** [comment]
> > > @tommy04062019 Sorry but since I'm failed to reproduce the error you encountered, could you help to provide more information about your test steps? Like how/what you created/deleted the test files? did you take snapshots or do any other operations? And if other environment information like OS, k8s distro version can be provided would be very appreciated. Thank you!
> > 
> > 
> > This is my environment:
> > ```
> > * Rancher : v2.5.15 (or v2.7.0)
> > 
> > * Kubernetes Version: v1.21.12
> > 
> > * OS worker: Ubuntu 20.04
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is how I tested created/deleted files.
> > ```
> > * After pod is running I access to shell
> > 
> > * cd to the mountpoint of Longhorn volume in the pod.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > dd if=/dev/zero of=2gbfile-1 bs=2G count=1
> > dd if=/dev/zero of=2gbfile-2 bs=2G count=1
> > sync
> > rm 2gbfile-1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > * On Longhorn UI, I did not take any snapshots, I just go to the volume and execute `Trim Filesystem` function.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Tell me if you need more info. Thank
> 
> With `ubuntu 20.04` + `k3s v1.21.12+k3s1` + `longhorn v1.4.x-head` and following the above operations, I'm still unable to reproduce this. Currently I don't have any clue. @derekbit Do you have any insight into what will possibly cause this error?

@yangchiu : I have just tested agained, what a surprise, somehow it works. I'm sure I haven't changed anything since reporting this bug. This error not only shows up once but many times. May be I will tested on new cluster one more time. Let's wait and see

**Comment by tommy04062019** [comment]
@yangchiu : I tested with new install on another cluster. It seems ok now. Need more time to obverse it, I will report then if it happen again. Also, I have a question:
- If I have hundred to thousands volumes, I have to go to Longhorn UI and trigger `Trim Filesystem` manually, right? Do we have any way to do this automatically?

**Comment by derekbit** [comment]
> Do we have any way to do this automatically?

@tommy04062019 
No for now. Can you create a ticket for the feature request?

**Comment by tommy04062019** [comment]
> > Do we have any way to do this automatically?
> 
> @tommy04062019 No for now. Can you create a ticket for the feature request?
> 
Yeah, sure, I will create one
> BTW, I cannot reproduce the IO error as well. You can provide the support bundle for futher investigation if encounter it again. Thank you.

May be there are something wrong with Longhorn on my old cluster. It works on a new Longhorn cluster, I will check this more closely, will inform u with the bundle when having failed.

**Comment by innobead** [comment]
@tommy04062019 https://github.com/longhorn/longhorn/issues/4932 is planned.

**Comment by derekbit** [comment]
> @derekbit Are we able to trim filesystem for a `RWX` volume?
> 
> I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> 
> And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`

@yangchiu 
For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`.
A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation. Let me create a ticket for the RWX trim feature.

**Comment by innobead** [comment]
We should add this limitation together with #5128 , but need to think of a validation way to avoid this unsupported operation.

**Comment by tommy04062019** [comment]
> > @derekbit Are we able to trim filesystem for a `RWX` volume?
> > I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> > And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`
> 
> @yangchiu For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`. A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation instead of `nsenter .... fstrim <mountpoint>`. Let me create a ticket for the RWX trim feature.

@derekbit : I got 1 error while using RWX Volume (On v1.3.0, v1.3.2, v1.4.x)
<img width="1440" alt="Screen Shot 2022-12-23 at 17 29 04" src="https://user-images.githubusercontent.com/8014325/209321362-cd422cba-558d-484e-872d-beb3d749a680.png">

Maybe I should create another ticket for it.

**Comment by derekbit** [comment]
> > > @derekbit Are we able to trim filesystem for a `RWX` volume?
> > > I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> > > And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`
> > 
> > 
> > @yangchiu For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`. A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation instead of `nsenter .... fstrim <mountpoint>`. Let me create a ticket for the RWX trim feature.
> 
> @derekbit : I got 1 error while using RWX Volume (On v1.3.0, v1.3.2, v1.4.x) <img alt="Screen Shot 2022-12-23 at 17 29 04" width="1440" src="https://user-images.githubusercontent.com/8014325/209321362-cd422cba-558d-484e-872d-beb3d749a680.png">
> 
> Maybe I should create another ticket for it.

Yeah, please provide us the steps and support bundle. Many thanks. :)

**Comment by tommy04062019** [comment]
> > > > @derekbit Are we able to trim filesystem for a `RWX` volume?
> > > > I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> > > > And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`
> > > 
> > > 
> > > @yangchiu For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`. A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation instead of `nsenter .... fstrim <mountpoint>`. Let me create a ticket for the RWX trim feature.
> > 
> > 
> > @derekbit : I got 1 error while using RWX Volume (On v1.3.0, v1.3.2, v1.4.x) <img alt="Screen Shot 2022-12-23 at 17 29 04" width="1440" src="https://user-images.githubusercontent.com/8014325/209321362-cd422cba-558d-484e-872d-beb3d749a680.png">
> > Maybe I should create another ticket for it.
> 
> Yeah, please provide us the steps and support bundle. Many thanks. :)

Sorry, it's my fault,I forgot to install nfs client on worker nodes:)

**Comment by tommy04062019** [comment]
> > @derekbit Are we able to trim filesystem for a `RWX` volume?
> > I create a workload using Longhorn RWX volume: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml`
> > And try to trim filesystem from Longhorn UI, it gives the following error message: `unable to trim filesystem for volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f: cannot find volume pvc-dd108b65-2e23-46dd-aaf6-bf3f38ac383f mount info on host: failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net fstrim ], output , stderr fstrim: cannot get realpath: : No such file or directory : exit status 1`
> 
> @yangchiu For a RWX volume, the `/dev/longhorn/xxxx` is mounted to `/export/xxxx` in a share-manager pod, so you cannot see the mountpoint on the host and hence got the error message `No such file or directory`. A NFS mountpoint doesn't support discard/trim operation as well. For the RWX volumes, need to figure out a way to do trim operation instead of `nsenter .... fstrim <mountpoint>`. Let me create a ticket for the RWX trim feature.

@derekbit : I just tested case with RWX. I think we can somehow access to `shared-manager` pod from `instance-manager-e-...` pod  when trigger `Trim Filesystem` on RWX volume, so  fstrim job will be executed in `shared-manager-<pvc-name>` pod. 
Steps to test:
- Create a workload using RWX with 1GB of data.
- Create one test file with 200MB: `dd if=/dev/zero of=test bs=200M count=1`
<img width="1434" alt="Screen Shot 2022-12-23 at 20 13 52" src="https://user-images.githubusercontent.com/8014325/209343702-a703b5e2-a96c-4db4-821d-5f8426232348.png">

- Delete `test` file --> Trigger `Trim Filesystem` --> Error as above
- Try to access to `shared-manager-<pvc-name>` pod and run `fstrim` with the volume
<img width="1120" alt="Screen Shot 2022-12-23 at 20 24 19" src="https://user-images.githubusercontent.com/8014325/209343305-a2762925-3971-48be-8f88-09390f4d98f1.png">
- And then Longhorn UI shown as expected. Volume was trimmed
<img width="1427" alt="Screen Shot 2022-12-23 at 20 25 07" src="https://user-images.githubusercontent.com/8014325/209343415-11a028f1-dbe5-4b5d-aaee-782bf21fe4d1.png">

**Comment by innobead** [comment]
Thanks, @tommy04062019 , this is good feedback as you have done this to the mount point in the share manager pod. This will be the way when we implement trim support for RWX volume.

**Comment by innobead** [comment]
@yangchiu I will hang over the remaining testing to you and let's wrap this up. Thanks.

**Comment by yangchiu** [comment]
@derekbit Will we show any message on UI when trying to trim a volume with backing image?

**Comment by yangchiu** [comment]
@derekbit Do we support trim an encrypted volume?

**Comment by innobead** [comment]
> @derekbit Will we show any message on UI when trying to trim a volume with backing image?

Timing a volume backed by a backing image is supported, even the layer/disk of the backing image will not be altered. Therefore, there is no specific message for it IIRC. Do you think we should notice users?

> @derekbit Do we support trim an encrypted volume?

No, due to https://github.com/longhorn/longhorn-manager/pull/1613#issuecomment-1352559588. We need to mention this in the doc, https://longhorn.io/docs/1.4.0/volumes-and-nodes/trim-filesystem/. @shuo-wu

**Comment by yangchiu** [comment]
> > @derekbit Will we show any message on UI when trying to trim a volume with backing image?
> 
> Timing a volume backed by a backing image is supported, even the layer/disk of the backing image will not be altered. Therefore, there is no specific message for it IIRC. Do you think we should notice users?
> 
Not sure if we need document for this or not?

**Comment by yangchiu** [comment]
Verified passed on v1.4.x-head (longhorn-manager 413f2b3).

- Create Longhorn volume from UI or dynamic provisioning, the volume can be trimmed without error.
- For RWX volume or encrypted volume, trigger trim filesystem will show no valid mount point error message on UI.
- For volume with backing image, trigger trim filesystem will do nothing, and won't show any message on UI.

**Comment by innobead** [comment]
> * For volume with backing image, trigger trim filesystem will do nothing, and won't show any message on UI.

@yangchiu Could you test this again after adding/removing some data to the volume backed by a backing image? See if the removed data actually trimmed. 

cc @derekbit

**Comment by innobead** [comment]
> > > @derekbit Will we show any message on UI when trying to trim a volume with backing image?
> > 
> > 
> > Timing a volume backed by a backing image is supported, even the layer/disk of the backing image will not be altered. Therefore, there is no specific message for it IIRC. Do you think we should notice users?
> 
> Not sure if we need document for this or not?

YES, we need to update the doc https://longhorn.io/docs/1.4.0/volumes-and-nodes/trim-filesystem/ before closing this issue. @shuo-wu

**Comment by yangchiu** [comment]
> > * For volume with backing image, trigger trim filesystem will do nothing, and won't show any message on UI.
> 
> @yangchiu Could you test this again after adding/removing some data to the volume backed by a backing image? See if the removed data actually trimmed.
> 
> cc @derekbit

Tested on v1.4.x-head:

(1) Create a volume with backing image of size 1.1 Mi, the actual size shown on Longhorn UI is 1.1 Mi
(2) Write extra 16 Mi data to the volume, and then delete it:
```
# dd if=/dev/urandom of=/data/guests/test-1 bs=1M count=16
# rm /data/guests/test-1
```
(3) The actual size shown on Longhorn UI becomes 17.2 Mi
(4) Trigger trim filesystem, the actual size is back to 1.1 Mi

**Comment by innobead** [comment]
The doc has been updated. Closing the issue.

**Comment by derekbit** [comment]
> Is the size shrinking feature in engine V1 (no just trimming) part of the roadmap of the project ?

It is a limitation of Kubernetes. Kubernetes does not support shrinking a PVC to less than its current size.
Ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
