### ISSUE TITLE
[BUG] Some volumes stuck in "Attaching" state after upgrade to 1.7.0

### ISSUE THREAD

**Issue by DerFetzer** [longhorn/longhorn#9267]
## Describe the bug

Before doing the upgrade from 1.6.0 to 1.7.0 I scaled all my workloads down. When scaling the workloads back up after the update a third of the volumes got stuck in "Attaching" state.

## To Reproduce

Scale workloads with volumes down. Do upgrade from 1.6.0 to 1.7.0. Then scale the workloads back up.

## Expected behavior

All volumes get attached correctly.

## Support bundle for troubleshooting

I will send the bundle via mail.

## Environment

 - Longhorn version: 1.7.0
 - Impacted volume (PV): pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b
 - Installation method: Helm
 - Kubernetes distro and version: RKE v1.6.1 (v1.28.12-rancher1-1)
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 6
 - Node config
   - OS type and version: Ubuntu 22.04.4 LTS
   - Kernel version: 6.8.0-40-generic
   - CPU per node: 4
   - Memory per node: 16 GB
   - Disk type: SSD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure: KVM-based cloud server
 - Number of Longhorn volumes in the cluster: 37

## Additional context

When scaling the workloads back down they get detached correctly. When attaching the volumes manually to a node they are getting stuck as well and can only be detached by API call. With maintenance mode activated it is the same.

This is independent from the node since there are correctly attached and attaching volumes on the same node.

When creating the support bundle volume `pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b` was stuck in attaching to host rs1 while `pvc-37e0cc3d-d71c-44ca-b77b-4e23fabcc6f6` was attached correctly to the same host.

The volumes that are affected are always the same, but I could not determine what they have in common.

## Workaround and Mitigation

https://github.com/longhorn/longhorn/issues/9267#issuecomment-2301767750

--

**Comment by gcarrarom** [comment]
Hi, just having the same issue. I've realized mine are all RWX volumes. Can you confirm if that's the same for you?

**Comment by gcarrarom** [comment]
Same thing happened to me. Thankfully my last backup wasn't too far and most services weren't that important. Deleting the Volumes and restoring them from backup did the trick to restore the state of the volumes.

**Comment by derekbit** [comment]
@DerFetzer @gcarrarom 
What's the workloads (deployment, daemonset or stateulset) and volume type (RWO or RWX)?

**Comment by roger-ryao** [comment]
**The test steps**

I used the following steps to upgrade from `v1.6.0` to `v1.7.0` using both the `manifest` and `Helm chart`, not only for `RWO` but also for `RWX`, but I couldn't reproduce the issue.:

1. Install Longhorn version 1.6.0.
2. Create 40 deployments
    <details>
    <summary>Create 40 deployments</summary>
    
    ```bash

    #!/bin/bash
    
    for i in {1..40}; do
      cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rwo-volume-pvc-$i
      namespace: default
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app-$i
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app-$i
      template:
        metadata:
          labels:
            app: app-$i
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwo-volume-pvc-$i
          volumes:
          - name: rwo-volume-pvc-$i
            persistentVolumeClaim:
              claimName: rwo-volume-pvc-$i
    EOF
    done
    ```

    </details>

3. Scale down the first 20 deployments to 0 replicas.

    <details>

    <summary>Scale down</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..20}; do
      kubectl scale deployment app-$i --replicas=0 -n default
    done
    ```
    
    </details>

4. Upgrade Longhorn to version 1.7.0.
5. Scale down the remaining 20 deployments to 0 replicas.

    <details>

    <summary>Scale up</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..20}; do
      kubectl scale deployment app-$i --replicas=1 -n default
    done
    ```

    </details>

**Comment by derekbit** [comment]
@DerFetzer Can you help check the CPU is very busy on your cluster?

**Comment by derekbit** [comment]
cc @mantissahz the coordinator of this sprint

**Comment by DerFetzer** [comment]
> @gcarrarom What's the workloads (deployment, daemonset or stateulset) and volume type (RWO or RWX)?
>
Deployment and Statefulset are affected. All volumes are RWO. I only use one RWX volume and this can be attached without problems.

> @DerFetzer Can you help check the CPU is busy on your cluster?
>
CPU usage is very low on the nodes.

> BTW, I saw you change the setting `log-level` to `Debug`. Can you revert it to `Info` and see if the engine can be successfully attached?
>
I must have changed this a long time ago. Switching it back to INFO did not help.

**Comment by derekbit** [comment]
Can you 

> > @gcarrarom What's the workloads (deployment, daemonset or stateulset) and volume type (RWO or RWX)?
> 
> Deployment and Statefulset are affected. All volumes are RWO. I only use one RWX volume and this can be attached without problems.
> 
> > @DerFetzer Can you help check the CPU is busy on your cluster?
> 
> CPU usage is very low on the nodes.
> 
> > BTW, I saw you change the setting `log-level` to `Debug`. Can you revert it to `Info` and see if the engine can be successfully attached?
> 
> I must have changed this a long time ago. Switching it back to INFO did not help.

OK. Can you detach `pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b`, then attach it and generate a support bundle again? I would like to exclude the annoying debug messages.

**Comment by roger-ryao** [comment]
@derekbit 
I couldn't reproduce the issue following these steps:

**The test steps**

1. Install Longhorn version `v1.6.0`.
2. Create 40 deployments
    <details>
    <summary>Create 40 deployments</summary>
    
    ```bash

    #!/bin/bash
    
    for i in {1..40}; do
      cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rwo-volume-pvc-$i
      namespace: default
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app-$i
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app-$i
      template:
        metadata:
          labels:
            app: app-$i
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwo-volume-pvc-$i
          volumes:
          - name: rwo-volume-pvc-$i
            persistentVolumeClaim:
              claimName: rwo-volume-pvc-$i
    EOF
    done
    ```

    </details>
3. Upgrade Longhorn to version `v1.7.0`.
4. Scale down the 40 deployments to 0 replicas.

    <details>

    <summary>scale_down_deployments.sh</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..40}; do
      kubectl scale deployment app-$i --replicas=0 -n default
    done
    ```
    
    </details>

5. Scale up the remaining 40 deployments to 1 replicas.

    <details>

    <summary>scale_up_deployments.sh</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..20}; do
      kubectl scale deployment app-$i --replicas=1 -n default
    done
    ```

    </details>

6. Repeat steps 4 and 5 for 10 rounds.

    <details>

    <summary>repeat_scale.sh</summary>

    ```bash
    #!/bin/bash

    for i in {1..10}
    do
        echo "Iteration $i"
        echo "Scaling up deployments..."
        ./scale_up_deployments.sh
        echo "Waiting for 180 seconds..."
        sleep 180
    
        echo "Scaling down deployments..."
        ./scale_down_deployments.sh
        echo "Waiting for 180 seconds..."
        sleep 180
    
        echo "Iteration $i completed"
        echo "-------------------------"
    done

    echo "All iterations completed"
    ```
    
    </details>

**Comment by derekbit** [comment]
This is weird. The engines in the instance-managers are marked as `engine` in your cluster.

```
      pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b-e-7e64327e:
        spec:
          backendStoreDriver: "null"
          dataEngine: v1
          name: pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b-e-7e64327e
        status:
          conditions: "null"
          endpoint: "null"
          errorMsg: "null"
          listen: "null"
          portEnd: 10010
          portStart: 10010
          resourceVersion: 0
          state: running
          targetPortEnd: 0
          targetPortStart: 0
          type: replica
```
cc @ChanYiLin

**Comment by ChanYiLin** [comment]
Hi @DerFetzer @gcarrarom 
We believe the root cause is that we change the engine naming pattern after `v1.4.4` and `1.5.2`
And the new regex doesn't recognize the old naming pattern like this one `pvc-3308aae1-b3c4-4ea3-a6b8-d1fc16cea03b-e-7e64327e` which has a uuid string after `-e-`
As a result, Longhorn didn't find the engine and didn't update the status of it to running in your case. The volume then kept in `attaching` state.

I have hot fix the bug and build an image `jackfantasy/longhorn-manager:fix_v170_issue9267`
If you don't mind to try, it should fix the issues automatically since Longhorn periodically polls the status of all the engines.
With my hot fix image, Longhorn should find the engine and update the status to running and make the volume `attached`.

To update the image
```
$ kubectl edit daemonset/longhorn-manager -n longhorn-system
1. update the "spec.template.spec.containers[0].command" argument "--manager-image" to `jackfantasy/longhorn-manager:fix_v170_issue9267`
2. update the "spec.template.spec.containers[0].image" to `jackfantasy/longhorn-manager:fix_v170_issue9267`
```

Can you help to try and see if the image fix the issue. Thanks very much!

cc @derekbit

**Comment by DerFetzer** [comment]
Hi @ChanYiLin,

thank you very much!

Unfortunately it does not fix the problem.
Do you need another support bundle?

**Comment by ChanYiLin** [comment]
Hi @DerFetzer  
Sorry we are working on it
It seems we need to replace longhorn-instance-manager as well

cc @derekbit

**Comment by DerFetzer** [comment]
@ChanYiLin no need to apologize! You are doing great work!

**Comment by DerFetzer** [comment]
@derekbit
I added the images to my helm config:
```yaml
image:
  longhorn:
    manager:
      repository: derekbit/longhorn-manager
      tag: v1.7.0_issue9267
    instanceManager:
      repository: derekbit/longhorn-instance-manager
      tag: v1.7.0_issue9267
```
When I do the helm upgrade I get:
```shell
❯ helm upgrade longhorn longhorn/longhorn --values longhorn_config.yml
Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
        * job longhorn-pre-upgrade failed: BackoffLimitExceeded
```

Do I have to configure something else?

**Comment by derekbit** [comment]
@DerFetzer 
It seems the upgrade took a long time. Can you check if the longhorn-manager daemonset and instance-manager (lhim) resources's spec.image are updated in the end?

**Comment by DerFetzer** [comment]
@derekbit 
This message appears almost immediately and nothing gets updated.
There are those values in the chart:
```
preUpgradeChecker:
  # -- Setting that allows Longhorn to perform pre-upgrade checks. Disable this setting when installing Longhorn using Argo CD or other GitOps solutions.
  jobEnabled: true
  # -- Setting that allows Longhorn to perform upgrade version checks after starting the Longhorn Manager DaemonSet Pods. Disabling this setting also disables `preUpgradeChecker.jobEnabled`. Longhorn recommends keeping this setting enabled.
  upgradeVersionCheck: true
```
I think it fails there. Is it safe to disable this parameters?

**Comment by DerFetzer** [comment]
It is working!
Thank you very much for the great work!

**Comment by derekbit** [comment]
> It is working! Thank you very much for the great work!

@DerFetzer Awesome! Thanks for raising and helping verify the fix. We will release v1.7.1 including the fix soon.

cc @ChanYiLin @innobead

**Comment by gcarrarom** [comment]
Wow! Well done guys, just got to my computer to see all of this. Thanks for the quick work. Thankfully the workaround for me was enough - deleting and recovering from latest backup. But I'm happy nobody else is going to need doing this!

**Comment by roger-ryao** [comment]
Update reproduce the issue following these steps:

**The test steps**

1. Install Longhorn version `v1.5.1`.
2. Set `concurrent-automatic-engine-upgrade-per-node-limit` to 3
3. Create 20 deployments
    <details>
    <summary>Create 20 deployments</summary>
    
    ```bash

    #!/bin/bash
    
    for i in {1..20}; do
      cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: rwo-volume-pvc-$i
      namespace: default
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app-$i
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: app-$i
      template:
        metadata:
          labels:
            app: app-$i
        spec:
          containers:
          - name: app
            image: busybox
            command: ["/bin/sh", "-c", "exec 7<>/data/testfile-$(hostname -s); flock -x 7; while date | dd conv=fsync >&7 ; do sleep 1; done"]
            volumeMounts:
            - mountPath: /data
              name: rwo-volume-pvc-$i
          volumes:
          - name: rwo-volume-pvc-$i
            persistentVolumeClaim:
              claimName: rwo-volume-pvc-$i
    EOF
    done
    ```

    </details>
4. Scale down the 10 deployments to 0 replicas.

    <details>

    <summary>scale_down_deployments.sh</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..10}; do
      kubectl scale deployment app-$i --replicas=0 -n default
    done
    ```
    
    </details>
5. Upgrade Longhorn to version `v1.6.0`.
6. Upgrade Longhorn to version `v1.7.0`
7. Scale up the remaining 10 deployments to 1 replicas.

    <details>

    <summary>scale_up_deployments.sh</summary>

    ```bash
    #!/bin/bash
    
    for i in {1..10}; do
      kubectl scale deployment app-$i --replicas=1 -n default
    done
    ```

    </details>

**Comment by roger-ryao** [comment]
**Verified on master-head/v1.7.x 20230823**

- longhorn master-head https://github.com/longhorn/longhorn/commit/3c193680a92aac10d20f642c0dc130391781cb43
- longhorn-manager master-head https://github.com/longhorn/longhorn-manager/commit/555af1ed5603b2d1afe889ade722f497d5fc6750
- longhorn-instance-manager master-head https://github.com/longhorn/longhorn-instance-manager/commit/7d9aee16a685bbe5c5fe7ffd02fe3a4fe7fc711a

- longhorn v1.7.x-head https://github.com/longhorn/longhorn/commit/e2bb3e67a5da52c11ba14b6c093b815552ef6402
- longhorn-manager v1.7.x-head https://github.com/longhorn/longhorn-manager/commit/afeb9acb742b1b693dc091bc13ad20fca6aacf13
- longhorn-instance-manager v1.7.x-head https://github.com/longhorn/longhorn-instance-manager/commit/db39f71745f66276252940ac685d46bf37e139dd

**The test steps**
https://github.com/longhorn/longhorn/issues/9267#issuecomment-2303607612

**Result Passed**

Test passed with the following steps:
1. Install Longhorn version `v1.5.1`, upgrade to version `v1.6.0`, and then upgrade to version `v1.7.x-head`.
2. Install Longhorn version `v1.5.1`, upgrade to version `v1.6.0`, then to version `v1.7.0`, and finally to `master-head`.

**Comment by derekbit** [comment]
@sachintiptur Please check https://longhorn.io/docs/1.7.0/important-notes/#unable-to-attach-volumes-created-before-v152-and-v144 and the command.
We will release v1.7.1 soon, so you can wait for a while. :)

**Comment by derekbit** [comment]
> The command returns 'safe to upload' but it is checking for 8 characters but in our case we have one character. So I wanted to double confirm before upgrading.

Yes, it is safe for your cluster. :)

**Comment by rogerrum** [comment]
@derekbit Can we have the linux/arm64 version of the images - derekbit/longhorn-manager:v1.7.0_issue9267
derekbit/longhorn-instance-manager:v1.7.0_issue9267

The fix is working but arm64 nodes can run those two images.

**Comment by roger-ryao** [comment]
> The fix is working but arm64 nodes can run those two images.
Hi @rogerrum 
     The fix was merged last week. You can test it with `v1.7.x-head` or wait for the `v1.7.1` release, which should be out in the next few days if everything goes as planned.

**Comment by derekbit** [comment]
> @derekbit Can we have the linux/arm64 version of the images - derekbit/longhorn-manager:v1.7.0_issue9267 derekbit/longhorn-instance-manager:v1.7.0_issue9267
> 
> The fix is working but arm64 nodes can run those two images.

Hello @rogerrum,

The images I mentioned in https://github.com/longhorn/longhorn/issues/9267#issuecomment-2301767750 supports arm64 as well now. But, as @roger-ryao said, v1.7.1 with the fix will be released this week. You can wait for a while.
